import { StyleSheet, Platform } from "react-native";
import {
  COLORS,
  FONT_SIZES,
  FONT_WEIGHT,
  FONT_FAMILY,
  PADDINGS,
  getShadowStyle,
  getGlassShadow,
  getGlassStyle,
} from "../../../styles/theme";

const CARD_RADIUS = 20;

const styles = StyleSheet.create({
  keyboardView: { flex: 1, backgroundColor: "transparent" },
  contentCard: {
    flex: 1,
    marginHorizontal: PADDINGS.screenEdge,
    marginBottom: PADDINGS.tabBarSafeBottom,
    backgroundColor: COLORS.white,
    borderRadius: CARD_RADIUS,
    overflow: "hidden",
    ...getShadowStyle({ y: 2, blur: 12, opacity: 0.08, elevation: 6 }),
  },
  mainContainer: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: PADDINGS.screenEdge,
    paddingTop: Platform.OS === "web" ? 24 : 24,
    paddingBottom: PADDINGS.tabBarSafeBottom,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 4,
    paddingVertical: 12,
    marginBottom: 8,
  },
  backButton: {
    padding: 8,
    marginLeft: -8,
  },
  // Invisible left spacer that mirrors headerEditButton's footprint so the
  // title stays centered now that the profile tab root has no back button.
  headerSpacer: {
    width: 40,
  },
  headerTitle: {
    flex: 1,
    textAlign: "center",
    fontSize: FONT_SIZES.headerTitle,
    fontWeight: FONT_WEIGHT.boldFontBig,
    color: COLORS.blackText,
    fontFamily: FONT_FAMILY.semiBold,
  },
  headerEditButton: {
    ...getGlassStyle("neutral"),
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  avatarContainer: {
    alignItems: "center",
    marginBottom: 16,
  },
  avatarCircle: {
    width: 96,
    height: 96,
    borderRadius: 48,
    backgroundColor: COLORS.secondary,
    alignItems: "center",
    justifyContent: "center",
  },
  avatarInitials: {
    fontSize: 32,
    fontWeight: FONT_WEIGHT.boldFontBig,
    color: COLORS.whiteText,
    fontFamily: FONT_FAMILY.semiBold,
  },
  avatar: {
    width: 96,
    height: 96,
    borderRadius: 48,
  },
  fullName: {
    fontSize: FONT_SIZES.pageTitle,
    fontWeight: FONT_WEIGHT.boldFontBig,
    color: COLORS.blackText,
    textAlign: "center",
  },
  fullNameUnderAvatar: {
    fontSize: FONT_SIZES.subtitle1,
    fontWeight: FONT_WEIGHT.boldFontBig,
    color: COLORS.blackText,
    textAlign: "center",
    marginTop: 12,
    fontFamily: FONT_FAMILY.semiBold,
  },
  emailUnderAvatar: {
    fontSize: FONT_SIZES.inputText,
    color: COLORS.greyText,
    textAlign: "center",
    marginTop: 4,
    fontFamily: FONT_FAMILY.regular,
  },
  memberSinceText: {
    fontSize: FONT_SIZES.xsText,
    color: COLORS.greyText,
    textAlign: "center",
    marginTop: 6,
    fontFamily: FONT_FAMILY.regular,
  },
  sectionTitleCard: {
    fontSize: FONT_SIZES.subtitle2,
    fontWeight: FONT_WEIGHT.boldFontBig,
    color: COLORS.blackText,
    marginBottom: 12,
    fontFamily: FONT_FAMILY.semiBold,
  },
  infoCard: {
    backgroundColor: COLORS.white,
    borderRadius: 16,
    paddingVertical: 14,
    paddingHorizontal: 16,
    marginBottom: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    ...getShadowStyle({ y: 1, blur: 6, opacity: 0.06, elevation: 3 }),
  },
  infoCardLeft: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
    minWidth: 0,
    marginRight: 8,
  },
  infoCardRight: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    flexShrink: 0,
  },
  infoCardIcon: {
    marginRight: 12,
  },
  infoCardLabel: {
    fontSize: FONT_SIZES.inputText,
    fontWeight: FONT_WEIGHT.boldFont,
    color: COLORS.blackText,
    fontFamily: FONT_FAMILY.regular,
    flexShrink: 1,
  },
  infoCardValue: {
    fontSize: FONT_SIZES.inputText,
    color: COLORS.greyText,
    marginLeft: 8,
    fontFamily: FONT_FAMILY.regular,
  },
  infoCardButton: {
    paddingVertical: 6,
    paddingHorizontal: 14,
    borderRadius: 10,
    backgroundColor: "rgba(255,255,255,0.28)",
    borderWidth: 1,
    borderColor: "rgba(112, 193, 227, 0.6)",
    flexShrink: 0,
    ...getGlassShadow({ y: 2, blur: 8, opacity: 0.08 }),
  },
  infoCardButtonText: {
    fontSize: FONT_SIZES.xsText,
    fontWeight: FONT_WEIGHT.boldFont,
    color: COLORS.secondary,
    fontFamily: FONT_FAMILY.regular,
  },
  avatarEditButton: {
    position: "absolute",
    bottom: 0,
    right: "50%",
    marginRight: -48 - 20,
    backgroundColor: COLORS.secondary,
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  infoBlock: {
    marginBottom: 8,
  },
  infoRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 14,
  },
  infoIcon: {
    marginTop: 2,
    marginRight: 10,
  },
  infoLabel: {
    fontSize: FONT_SIZES.xsText,
    fontWeight: FONT_WEIGHT.boldFont,
    color: COLORS.greyText,
    marginBottom: 2,
    fontFamily: FONT_FAMILY.semiBold,
  },
  infoValue: {
    fontSize: FONT_SIZES.inputText,
    color: COLORS.blackText,
    flex: 1,
    fontFamily: FONT_FAMILY.regular,
  },
  editIconWrap: {
    marginRight: 10,
    padding: 4,
  },
  infoLabelValue: {
    flex: 1,
  },
  inlineInput: {
    fontSize: FONT_SIZES.inputText,
    color: COLORS.blackText,
    paddingVertical: 6,
    paddingHorizontal: 0,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.secondary,
    minHeight: 32,
  },
  scheduleVideoButton: {
    ...getGlassStyle("secondary"),
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 12,
    marginTop: 8,
    marginBottom: 24,
  },
  scheduleVideoButtonText: {
    fontSize: FONT_SIZES.inputText,
    fontWeight: FONT_WEIGHT.boldFont,
    color: COLORS.secondary,
    marginLeft: 8,
    fontFamily: FONT_FAMILY.regular,
  },
  card: {
    backgroundColor: COLORS.white,
    borderRadius: 16,
    padding: PADDINGS.screenEdge,
    marginBottom: 16,
    ...getShadowStyle({ y: 2, blur: 8, opacity: 0.06, elevation: 2 }),
  },
  sectionTitle: {
    fontSize: FONT_SIZES.subtitle2,
    fontWeight: FONT_WEIGHT.boldFontBig,
    color: COLORS.blackText,
    marginBottom: 14,
  },
  healthRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(0,0,0,0.06)",
  },
  healthRowLast: {
    borderBottomWidth: 0,
  },
  healthLabel: {
    fontSize: FONT_SIZES.inputText,
    color: COLORS.greyText,
  },
  healthValue: {
    fontSize: FONT_SIZES.inputText,
    color: COLORS.blackText,
  },
  tabRow: {
    flexDirection: "row",
    marginTop: 8,
    borderWidth: 1,
    borderColor: COLORS.secondary,
    borderRadius: 12,
    overflow: "hidden",
  },
  tab: {
    flex: 1,
    paddingVertical: 12,
    alignItems: "center",
  },
  tabActive: {
    backgroundColor: COLORS.secondary,
  },
  tabText: {
    fontSize: FONT_SIZES.xsText,
    fontWeight: FONT_WEIGHT.boldFont,
    color: COLORS.greyText,
  },
  tabTextActive: {
    color: COLORS.whiteText,
  },
  editSection: {
    marginTop: 16,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: "rgba(0,0,0,0.08)",
  },
  input: {
    backgroundColor: "#F5F7FA",
    borderWidth: 1,
    borderColor: "#E3E8EF",
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 12,
    fontSize: FONT_SIZES.inputText,
    color: COLORS.blackText,
    marginBottom: 12,
  },
  // Numeric field (weight/height): big centered number + persistent unit suffix.
  numberInputRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F5F7FA",
    borderWidth: 1,
    borderColor: "#E3E8EF",
    borderRadius: 14,
    paddingHorizontal: 18,
    height: 64,
    marginTop: 4,
  },
  numberInput: {
    flex: 1,
    fontSize: 28,
    fontWeight: FONT_WEIGHT.boldFont,
    color: COLORS.blackText,
    paddingVertical: 0,
  },
  numberUnit: {
    fontSize: 18,
    fontWeight: FONT_WEIGHT.boldFont,
    color: COLORS.greyText,
    marginLeft: 10,
  },
  numberHint: {
    fontSize: FONT_SIZES.xsText,
    color: COLORS.greyText,
    marginBottom: 8,
  },
  inputError: {
    borderWidth: 1,
    borderColor: COLORS.error,
  },
  errorText: {
    fontSize: 13,
    color: COLORS.error,
    marginTop: -8,
    marginBottom: 12,
  },
  saveButton: {
    ...getGlassStyle("primary"),
    paddingVertical: PADDINGS.mainButtonVertical,
    borderRadius: 12,
    alignItems: "center",
    marginTop: 16,
  },
  saveButtonText: {
    color: COLORS.selectedItem,
    fontSize: FONT_SIZES.mediumButtonText,
    fontWeight: FONT_WEIGHT.boldFont,
  },
  editFieldLabel: {
    fontSize: FONT_SIZES.xsText,
    fontWeight: FONT_WEIGHT.boldFont,
    color: COLORS.greyText,
    marginBottom: 6,
    marginTop: 4,
  },
  dateButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: COLORS.inputBackgeound,
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 14,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: COLORS.greyBorder,
  },
  dateButtonText: {
    fontSize: FONT_SIZES.inputText,
    color: COLORS.blackText,
    fontFamily: FONT_FAMILY.regular,
  },
  dateButtonPlaceholder: {
    color: COLORS.ligthGreyText,
  },
  chipRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 10,
  },
  chip: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.tagColor,
    paddingVertical: 8,
    paddingLeft: 12,
    paddingRight: 6,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(112, 193, 227, 0.4)",
  },
  chipText: {
    fontSize: FONT_SIZES.xsText,
    color: COLORS.blackText,
    fontFamily: FONT_FAMILY.regular,
    marginRight: 6,
    maxWidth: 180,
  },
  chipRemove: {
    padding: 4,
  },
  addRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 12,
  },
  addRowInput: {
    flex: 1,
    backgroundColor: COLORS.inputBackgeound,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: FONT_SIZES.inputText,
    color: COLORS.blackText,
    borderWidth: 1,
    borderColor: COLORS.greyBorder,
  },
  addButton: {
    ...getGlassStyle("primary"),
    paddingVertical: 10,
    paddingHorizontal: 18,
    borderRadius: 10,
    justifyContent: "center",
  },
  addButtonText: {
    fontSize: FONT_SIZES.inputText,
    fontWeight: FONT_WEIGHT.boldFont,
    color: COLORS.selectedItem,
    fontFamily: FONT_FAMILY.regular,
  },
  selectorRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 12,
  },
  selectorOption: {
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: COLORS.greyBorder,
    backgroundColor: COLORS.inputBackgeound,
  },
  selectorOptionSelected: {
    backgroundColor: COLORS.secondary,
    borderColor: COLORS.secondary,
  },
  selectorOptionText: {
    fontSize: FONT_SIZES.inputText,
    color: COLORS.blackText,
    fontFamily: FONT_FAMILY.regular,
  },
  selectorOptionTextSelected: {
    color: COLORS.blackText,
    fontWeight: FONT_WEIGHT.boldFont,
  },
  sectionSubLabel: {
    fontSize: FONT_SIZES.xsText,
    color: COLORS.greyText,
    marginBottom: 6,
    fontFamily: FONT_FAMILY.regular,
  },
  toggleRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
    gap: 8,
  },
  toggleLabel: {
    fontSize: FONT_SIZES.inputText,
    color: COLORS.blackText,
    fontFamily: FONT_FAMILY.regular,
    flex: 1,
  },
  reminderCard: {
    backgroundColor: COLORS.inputBackgeound,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.greyBorder,
    padding: 12,
    marginBottom: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  reminderCardTitle: {
    fontSize: FONT_SIZES.inputText,
    fontWeight: FONT_WEIGHT.boldFont,
    color: COLORS.blackText,
    fontFamily: FONT_FAMILY.regular,
  },
  reminderCardMeta: {
    fontSize: FONT_SIZES.xsText,
    color: COLORS.greyText,
    marginTop: 2,
    fontFamily: FONT_FAMILY.regular,
  },
  editProfileLinkText: {
    color: COLORS.secondary,
    fontWeight: FONT_WEIGHT.boldFont,
  },
  editScrollContent: {
    paddingBottom: PADDINGS.tabBarSafeBottom,
  },
  saveButtonBottom: {
    marginTop: 24,
    marginBottom: 24,
  },
  editProfileButton: {
    ...getGlassStyle("secondary"),
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: "center",
    marginTop: 16,
  },
  editProfileButtonText: {
    fontSize: FONT_SIZES.mediumButtonText,
    fontWeight: FONT_WEIGHT.boldFont,
    color: COLORS.secondary,
  },
  logoutButton: {
    ...getGlassStyle("danger"),
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 32,
    marginBottom: 24,
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 12,
  },
  logoutButtonText: {
    fontSize: FONT_SIZES.mediumButtonText,
    fontWeight: FONT_WEIGHT.boldFont,
    color: COLORS.error,
    marginLeft: 8,
    fontFamily: FONT_FAMILY.semiBold,
  },
  exportDataButton: {
    ...getGlassStyle("secondary"),
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 8,
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 12,
  },
  exportDataButtonText: {
    fontSize: FONT_SIZES.mediumButtonText,
    fontWeight: FONT_WEIGHT.boldFont,
    color: COLORS.secondary,
    marginLeft: 8,
    fontFamily: FONT_FAMILY.semiBold,
  },
  // Deliberately understated (a plain destructive text link, not a filled
  // button) so account deletion reads as secondary to logout.
  deleteAccountButton: {
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 32,
    paddingVertical: 8,
  },
  deleteAccountButtonText: {
    fontSize: FONT_SIZES.inputText,
    color: COLORS.error,
    textDecorationLine: "underline",
    fontFamily: FONT_FAMILY.regular,
  },
  infoRowReadOnly: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 14,
  },
  loaderContainer: {
    paddingTop: 90,
    alignItems: "center",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
    padding: 16,
  },
  modalBox: {
    width: "100%",
    maxWidth: 600,
    flex: 1,
    minHeight: 200,
    backgroundColor: COLORS.white,
    borderRadius: 16,
    overflow: "hidden",
  },
  modalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(0,0,0,0.08)",
  },
  modalTitle: {
    fontSize: FONT_SIZES.subtitle2,
    fontWeight: FONT_WEIGHT.boldFontBig,
    color: COLORS.blackText,
    fontFamily: FONT_FAMILY.semiBold,
  },
  modalCloseButton: {
    padding: 4,
  },
  modalLoader: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 40,
  },
  modalScroll: {
    flex: 1,
  },
  modalScrollContent: {
    padding: 16,
    paddingBottom: 32,
  },
  modalEmpty: {
    fontSize: FONT_SIZES.inputText,
    color: COLORS.greyText,
    textAlign: "center",
    paddingVertical: 24,
  },
  modalCard: {
    backgroundColor: COLORS.inputBackgeound,
    borderRadius: 12,
    padding: 14,
    marginBottom: 12,
  },
  modalCardTitle: {
    fontSize: FONT_SIZES.inputText,
    fontWeight: FONT_WEIGHT.boldFont,
    color: COLORS.blackText,
    marginBottom: 4,
    fontFamily: FONT_FAMILY.regular,
  },
  modalCardDate: {
    fontSize: FONT_SIZES.xsText,
    color: COLORS.greyText,
    marginBottom: 2,
  },
  modalCardMeta: {
    fontSize: FONT_SIZES.xsText,
    color: COLORS.greyText,
    marginTop: 2,
  },
  modalTags: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    marginTop: 6,
  },
  modalTag: {
    fontSize: 10,
    color: COLORS.secondary,
    backgroundColor: "rgba(112, 193, 227, 0.2)",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    overflow: "hidden",
  },
  modalPreviewText: {
    fontSize: FONT_SIZES.xsText,
    color: COLORS.greyText,
    marginTop: 6,
    lineHeight: 18,
  },
  // Collapsible ("dropdown") section: a tappable title header that shows/hides
  // its body (the grouped info/health cards).
  collapsibleWrap: {
    marginBottom: 12,
  },
  collapsibleHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: COLORS.white,
    borderRadius: 16,
    paddingVertical: 16,
    paddingHorizontal: 16,
    ...getShadowStyle({ y: 1, blur: 6, opacity: 0.06, elevation: 3 }),
  },
  collapsibleTitle: {
    fontSize: FONT_SIZES.subtitle2,
    fontWeight: FONT_WEIGHT.boldFontBig,
    color: COLORS.blackText,
    fontFamily: FONT_FAMILY.semiBold,
  },
  collapsibleBody: {
    marginTop: 10,
  },
  // Bottom-sheet container for the per-field edit overlay.
  fieldSheet: {
    width: "100%",
    maxWidth: 600,
    alignSelf: "center",
    backgroundColor: COLORS.white,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    overflow: "hidden",
  },
  // The per-field "Editar" action shown on the right of a health card.
  editLinkButton: {
    ...getGlassStyle("secondary"),
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 8,
  },
  editLinkButtonText: {
    fontSize: FONT_SIZES.xsText,
    fontWeight: FONT_WEIGHT.boldFont,
    color: COLORS.secondary,
    fontFamily: FONT_FAMILY.regular,
  },
});

export default styles;
