const STRINGS = {
  es: {
    speciality: {
      INT: "Medicina Interna",
      FAM: "Medicina Familiar y Comunitaria",
      PED: "Pediatría",
      GYN: "Ginecología y Obstetricia",
      PSY: "Psiquiatría",
      DER: "Dermatología",
      NEU: "Neurología",
      OPH: "Oftalmología",
      ENT: "Otorrinolaringología",
      ORT: "Traumatología y Ortopedia",
      SUR: "Cirugía General",
      ANE: "Anestesiología",
      ONC: "Oncología Médica",
      RAD: "Radiología / Diagnóstico por Imagen",
      EME: "Medicina de Urgencias / Emergencias",
      OCC: "Medicina del Trabajo",
      PMR: "Medicina Física y Rehabilitación",
      PRE: "Medicina Preventiva y Salud Pública",
      PSI: "Psicología",
      DEN: "Odontologia",
    },
    login: {
      title: "Bienvenido de nuevo",
      welcomeBack: "Bienvenido de nuevo",
      accessYourAccount: "Accede a tu cuenta",
      welfareMessage:
        "Tu salud es nuestra prioridad. Inicia sesión para gestionar tus citas y conectar con profesionales.",
      emailPlaceHolder: "Correo electrónico",
      passwordPlaceHolder: "Contraseña",
      logIn: "Iniciar sesión",
      forgotPassword: "Olvidaste tu contraseña",
      noAccount: "¿No tienes cuenta? ",
      haveAccount: "¿Ya tienes cuenta? ",
      createAccount: "Crear cuenta",
      orDivider: "o",
      rememberMe: "Recordarme",
      logInWithGoogle: "Iniciar con Google",
      logInWithApple: "Iniciar con Apple",
      country: "País ",
      countryName: "🇪🇨 Ecuador",
      language: "Idioma ",
      selectedLanguage: "Español",
      emailRequired: "Ingresa tu correo electrónico.",
      passwordRequired: "Ingresa tu contraseña.",
      invalidEmail: "El formato del correo electrónico no es válido.",
      accountBlockedTitle: "Cuenta bloqueada",
      accountBlockedMessage:
        "Tu cuenta ha sido bloqueada. Comunícate con soporte para más información.",
      understood: "Entendido",
    },
    forgotPasswordRequest: {
      title: "Restablecer contraseña",
      subtitle: "Ingresa tu correo electrónico",
      emailPlaceholder: "Correo electrónico",
      sendCode: "Enviar código",
      sending: "Enviando...",
      emailRequired: "Ingresa tu correo electrónico.",
      emailInvalid: "El formato del correo electrónico no es válido.",
      errorTitle: "Error",
      successTitle: "Éxito",
      genericError: "Ocurrió un error. Por favor, intenta nuevamente.",
    },
    forgotPasswordReset: {
      title: "Restablecer contraseña",
      subtitle: "Completa los campos a continuación",
      codeSentTo: "Se envió un código a: {email}",
      codePlaceholder: "Ingresa el código de restablecimiento",
      passwordPlaceholder: "Ingresa tu nueva contraseña",
      passwordConfirmPlaceholder: "Confirma tu nueva contraseña",
      resetPassword: "Restablecer contraseña",
      resetting: "Restableciendo...",
      fieldsRequired: "Completa todos los campos.",
      passwordInvalid:
        "La contraseña debe tener al menos 8 caracteres, un número y un carácter especial.",
      passwordMismatch: "Las contraseñas no coinciden.",
      errorTitle: "Error",
      successTitle: "Éxito",
      successMessage: "Tu contraseña se ha restablecido correctamente.",
      genericError: "No se pudo restablecer la contraseña. Intenta nuevamente.",
    },
    verifyEmail: {
      title: "Verifica tu correo",
      subtitle: "Ingresa el código de 6 dígitos que te enviamos",
      codeSentTo: "Se envió un código a: {email}",
      codePlaceholder: "Código de verificación",
      verify: "Verificar",
      resendCode: "Reenviar código",
      codeRequired: "Ingresa el código que recibiste por correo.",
      codeSent: "Código reenviado a tu correo.",
      success: "Correo verificado correctamente.",
      genericError: "No se pudo verificar el código. Intenta nuevamente.",
      missingContext: "Falta información para verificar el correo. Vuelve a iniciar sesión o regístrate de nuevo.",
      goToLogin: "Ir a inicio de sesión",
    },
    home: {
      search: "Buscar",
      findDoctor: "Buscar médico",
      greetingHello: "¡Hola, {name}!",
      greetingMessage: "Tu salud es nuestra prioridad.",
      dashHello: "Hola, {name}",
      dashHowAreYou: "¿Cómo te sientes hoy?",
      nextAppointment: "Próxima Cita",
      noNextAppointment: "No tienes citas en este momento.",
      specialties: "Especialidades",
      seeAll: "Ver todas",
      favoriteDoctors: "Médicos Favoritos",
      seeMore: "Ver más",
      allSpecialties: "Todas las especialidades",
      chipPediatrics: "Pediatría",
      chipCardiology: "Cardiología",
      chipDentistry: "Odontología",
      chipGeneral: "Medicina General",
      titleOne: "Tu Salud es",
      titleTwo: "nuestra prioridad",
      suggestion:
        '"Dormir bien, comer bien y respirar profundo también es productividad."',
      upcomingAppointments: "Próximas citas",
      seeAllAppointments: "Ver todas las citas",
      noUpcoming: "No tienes citas próximas.",
      welfareTips: [
        '"Dormir bien, comer bien y respirar profundo también es productividad."',
        '"Pequeños pasos diarios mejoran tu bienestar a largo plazo."',
        '"Tu salud mental es tan importante como tu salud física."',
        '"Hidratarse bien es uno de los mejores hábitos que puedes tener."',
        '"Una caminata corta al día puede cambiar cómo te sientes."',
      ],
    },
    findDoctor: {
      title: "Buscar médico",
      subtitle: "Elige una especialidad",
      seeDoctors: "Ver médicos",
      noDoctors: "No hay médicos en esta especialidad",
      tryAnother: "Prueba otra especialidad",
      errorLoading: "Error al cargar. Intenta de nuevo.",
      doctorCount: "médico",
      doctorCountPlural: "médicos",
    },
    signupUser: {
      createAccountTitle1: "Creá una\n",
      createAccountTitle2: "nueva cuenta",
      name: "NOMBRE",
      firstName: "NOMBRE(S)",
      firstNamePlaceholder: "Ejm: Juan",
      firstNameRequired: "Ingresa tu nombre.",
      lastName: "APELLIDO(S)",
      lastNamePlaceholder: "Ejm: Pérez",
      lastNameRequired: "Ingresa tu apellido.",
      nationalId: "CÉDULA",
      nationality: "NACIONALIDAD",
      nationalityPlaceholder: "Seleccione su nacionalidad",
      nationalityRequired: "Seleccione su nacionalidad",
      birthDate: "FECHA DE NACIMIENTO",
      phone: "CELULAR",
      province: "PROVINCIA",
      street: "CALLE",
      email: "CORREO ELECTRÓNICO",
      password: "CONTRASEÑA",
      passwordPlaceholder: "Ej: 1234@Abc",
      confirmPassword: "CONFIRMAR CONTRASEÑA",
      createAccountButton: "Crear cuenta",
      emailInvalid: "Correo electrónico inválido",
      passwordInvalid:
        "La contraseña debe tener al menos 8 caracteres, una mayúscula, una minúscula, un número y un símbolo",
      passwordMismatch: "Las contraseñas no coinciden",
      phoneInvalid: "Número de teléfono inválido",
      nationalIdInvalid: "Cédula inválida",
      birthDateInvalid: "La fecha debe estar en el pasado",

      error1: "Error al registrarse",
      namePlaceholder: "Ejm: Juan Pérez",
      phonePlaceholder: "0999999999",
      nationalIDPlaceholder: "1234567890",
      cancel: "Cancel",
      ok: "Ok",
      done: "Seleccionar",
      streetPlaceholder: "Ejm: Machala y Salinas",
      emailPlaceholder: "Ejm: ejemplo@gmail.com",
      emailDuplicate:
        "Un usuario con el correo {VAL} ya está en uso, intente resetear su clave",
      idDuplicate: "Un usuario con el cedula {VAL} ya esta en uso",
      errorFromDb: "Ha ocurrido un error intente nuevamente",
    },
    doctorSearch: {
      searchLabel: "Nombre, Especialidad",
      seachPlaceholder: "Buscar",
      SearchQueryIsRequired: "Se requiere un criterio de busqueda",
      errorOcured: "Ocurrió un error, intente nuevamente",
      filtersTitle: "Filtros",
      province: "Provincia",
      noDataFound: "No se encontraron resultados",
      cleanFiltersTitle: "Borrar filtros",
      offices: "Consultorios",
    },
    doctorProfile: {
      bookAppointment: "Agendar Cita",
      selectLocation: "Selecciona un consultorio:",
      phone: "Telefono:",
      email: "Correo:",
      schedule: "Horarios",
      languages: "Idiomas",
      paymentMethod: "Metodos de Pago",
      insurance: "Compañías de seguros",
      noInsurances: "No hay seguros cargados.",
      insurancePlan: "Plan",
      insurancePolicyNumber: "Nº de póliza",
      insuranceWebsite: "Sitio web",
      profile: "Perfil profesional",
      location: "Ubicación",
      selectLocationAlert: "Por favor seleccione un consultorio",
      morning: "Morning",
      afternoon: "Afternoon",
      fullDay: "Todo el dia",
      errorLoadingData:
        "Ocurrió un error al cargar los datos, intente nuevamente",
      errorBooking: "Ocurrió un error, intente nuevamente",
      seeLocation: "Ver ubicación",
      clinics: "Clínicas",
    },
    appointments: {
      myAppointments: "Mis Citas",
      nextAppointments: "Proximas Citas",
      pastAppointments: "Citas Pasadas",
      name: "Nombre:",
      speciality: "Especialidad: ",
      date: "Fecha: ",
      time: "Hora: ",
      location: "Lugar: ",
      status: "Estado: ",
      dateError:
        "Las citas solo se pueden cancelar por este medio hasta 12h antes de la consulta, pasado este tiempo debera comunicar se con el medico",
      cancelAppointment: "Cancelar Cita",
      bookAgain: "Agendar nuevamente",
      messageDoctor: "Enviar mensaje al médico",
      cancelationMessage: "Esta seguro que desea cancelar su cita?",
      cancelReasonPlaceholder: "Motivo de la cancelación (opcional)",
      cancellationReasonLabel: "Motivo de cancelación",
      confirmButton: "Confirmar",
      closeButton: "Cancelar",
      closeModal: "Cerrar",
      viewDetails: "Ver detalles",
      detailsTitle: "Detalles de Cita",
      appointmentInfo: "Información de la Cita",
      consultationType: "Tipo de Consulta",
      consultationMode: "Modo de Consulta",
      modeInPerson: "Presencial",
      modeVideo: "Videollamada",
      reschedule: "Reprogramar",
      scheduled: {
        cero: "Agendada",
        uno: "Finalizada",
      },
      pending: {
        cero: "Pendiente de confirmación",
        uno: "Pendiente de confirmación",
      },
      rescheduled: {
        cero: "Reprogramada",
        uno: "Reprogramada",
      },
      cancelled: {
        cero: "Cancelada",
        uno: "Cancelada",
      },
      bookNewAppointment: "Agendar cita",
      cancel: "Cancelar",
      noCurrent: "Actualmente no tiene citas",
      noPasst: "No tiene citas pasadas",
      timeRemainingDays: "{count} días",
      timeRemainingDay: "1 día",
      timeRemainingToday: "Hoy",
      timeRemainingTomorrow: "Mañana",
    },
    account: {
      myProfile: "Mi perfil",
      editProfile: "Editar datos de perfil",
      resetPassword: "Reestablecer contrasena",
      language: "Idioma",
      selectedLanguage: "Espanol",
      logOut: "Cerrar session",
      confirmLogOut: "Esta seguro?",
      languageSelect: "Selecione su idioma",
      closeButton: "Cancelar",
    },
    bookAppointment: {
      noSlots: "No se encuentran horarios disponibles para esta fecha",
      waitlistNotify: "Notificarme si se libera un horario",
      waitlistJoined: "Te notificaremos cuando se libere un horario",
      waitlistJoining: "Uniendo...",
      selectClinic: "Seleccione una clínica",
      selectDate: "Seleccione una fecha",
      selectType: "Seleccione el tipo de cita",
      timeSlots: "Horarios disponibles",
      confirmAppointment: "Confirmar Cita",
      errorDataDates: "Error al cargar las fechas",
      noAvailableDates: "No hay fechas disponibles",
      errorDataTimes: "Error al cargar los horarios",
      searchPlaceholder: "Buscar Doctor por nombre o especialidad",
      selectDoctor: "Seleccione un médico",
      morning: "Mañana",
      afternoon: "Tarde",
      noResults: "Sin resultados",
      clearSearch: "Cerrar búsqueda",
      changeHour: "Cambiar hora",
      bookingSuccess: "Cita agendada correctamente",
      bookingError: "No se pudo agendar la cita",
      createAppointmentWithDoctor: "Agendar cita",
    },
    daysOfWeek: [
      "Domingo",
      "Lunes",
      "Martes",
      "Miércoles",
      "Jueves",
      "Viernes",
      "Sábado",
    ],
    months: [
      "Enero",
      "Febrero",
      "Marzo",
      "Abril",
      "Mayo",
      "Junio",
      "Julio",
      "Agosto",
      "Septiembre",
      "Octubre",
      "Noviembre",
      "Diciembre",
    ],
    myProfile: {
      emailInvalid: "Correo electrónico inválido",
      phoneInvalid: "Número de teléfono inválido",
      nationalIdInvalid: "Cédula inválida",
      oldPasswordInvalid: "Debe ingresar la clave actual",
      passwordInvalid:
        "La contraseña debe tener al menos 8 caracteres, una mayúscula, una minúscula, un número y un símbolo",
      passwordMismatch: "Las contraseñas no coinciden",
      deleteCategory: "Eliminar Categoria",
      eliminar: "Eliminar",
      addCondition: "Agregar condición médica",
      selectCategory: "Seleccione una categoria",
      conditionPlaceholder: "Condición médica",
      addVaccine: "Agregar vacuna",
      vaccineNamePlaceholder: "Nombre de la vacuna",
      date: "Fecha",
      SelectDate: "Seleccione la fecha de la vacuna",
      details: "Datos personales",
      province: "Provincia",
      country: "Pais",
      height: "Altura (cm)",
      weight: "Peso (kg)",
      bloodType: "Tipo de sangre",
      bloodTypeSelect: "Selecciona tu tipo de sangre",
      gender: "Género",
      genderMale: "Masculino",
      genderFemale: "Femenino",
      genderDiverse: "Diverso",
      city: "Ciudad",
      parish: "Parroquia",
      languages: "Idiomas que hablas",
      languagesOptional: "Opcional",
      emergencyContact: "Contacto de emergencia",
      emergencyContactName: "Nombre del contacto",
      emergencyContactPhone: "Teléfono del contacto",
      emergencyContactRelationship: "Relación (ej. madre, esposo)",
      medicationReminders: "Recordatorios de medicamentos",
      medicationNamePlaceholder: "Nombre del medicamento",
      medicationDosePlaceholder: "Dosis (opcional)",
      medicationTime: "Hora del recordatorio",
      medicationReminderToggle: "Recordarme con una alarma",
      addMedication: "Añadir medicamento",
      noMedicationReminders: "No hay medicamentos con recordatorio agregados",
      vaccineReminderToggle: "Recordarme la próxima dosis",
      vaccineReminderDate: "Fecha del recordatorio",
      editYourProfile: "Edita tu perfil",
      medicalConditions: "Condiciónes médicas",
      vaccines: "Vacunas",
      save: "Guardar cambios",
      oldPassword: "Contraseña actual",
      newPassword: "Nueva contraseña",
      newPasswordConfirm: "Confirma tu nueva contraseña",
      savePassword: "Guardar nueva clave",
      sendCode: "Enviar código de confirmación",
      codeSent: "Código de confirmación enviado a tu correo.",
      codeSentMessage: "Ingresa el código de confirmación que enviamos a tu correo.",
      confirmationCode: "Código de confirmación",
      codeRequired: "Ingresa el código que recibiste por correo.",
      cancel: "Cancelar",
      changePassword: "Cambiar clave",
      closeAccount: "Eliminar cuenta",
      name: "Nombre",
      firstName: "Nombre(s)",
      firstNameRequired: "Ingresa tu nombre.",
      lastName: "Apellido(s)",
      lastNameRequired: "Ingresa tu apellido.",
      email: "E-Mail",
      phone: "Telefono",
      address: "Dirección",
      close: "Seleccionar",
      banerSuccess: "Datos actualizados con exito",
      banerError: "Hubo un error en la actualización de datos",
      noCondition:
        "No hay condiciones médicas agregadas, por favor agregue una",
      noVaccine: "No hay vacunas agregadas, por favor agregue una",
      banerErrorGetUser: "Hubo un error al obtener los datos del usuario",
      document: "Documento de Identidad",
      healthInfo: "Información de Salud",
      noDisponible: "No disponible",
      scheduleVideoCall: "Programar video llamada",
      clinicalHistory: "Historia Clínica",
      medications: "Medicamentos",
      allergies: "Alergias",
      allergyCountOne: "1 alergia",
      allergyCountOther: "{{count}} alergias",
      vaccineCountOne: "1 vacuna",
      vaccineCountOther: "{{count}} vacunas",
      editProfile: "Editar datos personales",
      accountSettings: "Cuenta",
      informationSection: "Información",
      dateOfBirth: "Fecha de nacimiento",
      profileTitle: "Perfil",
      noRegistrado: "No registrado",
      editShort: "Editar",
      sectionPhysical: "Datos físicos",
      sectionMedicalHistory: "Historial médico",
      sectionAccess: "Mis accesos",
      favoriteDoctors: "Médicos favoritos",
      waitlist: "Lista de espera",
      allergyAddPlaceholder: "Ej: Penicilina",
      add: "Añadir",
      noAllergies: "No hay alergias agregadas",
    },
    medicalCategories: [
      { label: "Enfermedades Infecciosas", value: "IFDI" },
      {
        label: "Enfermedades Cardiovasculares",
        value: "CVDI",
      },
      { label: "Enfermedades Respiratorias", value: "RSDI" },
      { label: "Trastornos Neurológicos", value: "NEDI" },
      { label: "Trastornos de Salud Mental", value: "MHDI" },
      {
        label: "Trastornos Endocrinos y Metabólicos",
        value: "EMDI",
      },
      {
        label: "Trastornos Musculoesqueléticos",
        value: "MSDI",
      },
      {
        label: "Trastornos Gastrointestinales",
        value: "GIDI",
      },
      {
        label: "Trastornos Genéticos y Congénitos",
        value: "GCDI",
      },
      {
        label: "Cánceres (Enfermedades Oncológicas)",
        value: "ONCO",
      },
      {
        label: "Afecciones Dermatológicas",
        value: "DERM",
      },
      {
        label: "Trastornos Renales y Urológicos",
        value: "RUDI",
      },
      {
        label: "Trastornos Hematológicos (de la Sangre)",
        value: "HEMD",
      },
      {
        label: "Trastornos de la Salud Reproductiva",
        value: "RHDI",
      },
      {
        label: "Trastornos del Sistema Inmunológico",
        value: "IMMU",
      },
      {
        label: "Trastornos Oculares (Oftalmología)",
        value: "OPHT",
      },
      {
        label: "Trastornos de Oído, Nariz y Garganta (ORL)",
        value: "ENTI",
      },
      {
        label: "Deficiencias Nutricionales",
        value: "NUDI",
      },
      { label: "Trastornos del Dolor", value: "PAIN" },
      { label: "Condiciones Toxicológicas", value: "TOXI" },
    ],
    medicalCategoryValues: {
      IFDI: "Enfermedades Infecciosas",
      CVDI: "Enfermedades Cardiovasculares",
      RSDI: "Enfermedades Respiratorias",
      NEDI: "Trastornos Neurológicos",
      MHDI: "Trastornos de Salud Mental",
      EMDI: "Trastornos Endocrinos y Metabólicos",
      MSDI: "Trastornos Musculoesqueléticos",
      GIDI: "Trastornos Gastrointestinales",
      GCDI: "Trastornos Genéticos y Congénitos",
      ONCO: "Cánceres (Enfermedades Oncológicas)",
      DERM: "Afecciones Dermatológicas",
      RUDI: "Trastornos Renales y Urológicos",
      HEMD: "Trastornos Hematológicos (de la Sangre)",
      RHDI: "Trastornos de la Salud Reproductiva",
      IMMU: "Trastornos del Sistema Inmunológico",
      OPHT: "Trastornos Oculares (Oftalmología)",
      ENTI: "Trastornos de Oído, Nariz y Garganta (ORL)",
      NUDI: "Deficiencias Nutricionales",
      PAIN: "Trastornos del Dolor",
      TOXI: "Condiciones Toxicológicas",
    },
    maps: {
      openGoogleMaps: "Abrir con Google Maps",
      openWays: "Abrir con Waze",
      openAppleMaps: "Abrir con Apple Maps",
      cencel: "Cancelar",
    },
    messages: {
      title: "Mensajes",
      consultation: "Consulta",
      available: "Disponible",
      timeAgoMin: "Hace {{n}} min",
      timeAgoHour: "Hace {{n}} h",
      timeAgoDay: "Hace {{n}} días",
      noMessages: "Sin mensajes",
      placeholder: "Los mensajes estarán disponibles pronto.",
      emptyConversations: "No tienes conversaciones aún.",
      emptyConversationsHint:
        "Abre una cita y pulsa «Enviar mensaje al médico» para iniciar una conversación.",
      typeMessage: "Escribe un mensaje...",
      send: "Enviar",
      loading: "Cargando...",
      errorLoad: "Error al cargar.",
      errorConversation: "No se pudo abrir la conversación.",
      videoCall: "Video llamada",
      joinVideoCallTitle: "Unirse a video llamada",
      videoCallCodePlaceholder: "Código de la sala",
      join: "Unirse",
      videoCallCodeRequired: "Ingresa el código de la sala.",
      videoCallJoinSuccess:
        "Código válido. La unión a la llamada se implementará próximamente.",
      videoCallRoomNotFound: "Sala no encontrada o código inválido.",
      videoCallRoomExpired: "La sala ha expirado.",
      videoCallTooEarly: "Disponible 5 min antes",
      videoCallEnded: "Llamada finalizada",
      videoCallConnecting: "Conectando...",
      videoCallLeave: "Salir de la llamada",
      videoCallLeaveTitle: "Salir de la llamada",
      videoCallLeaveMessage: "¿Estás seguro de que deseas salir?",
      videoCallLeaveConfirm: "Salir",
      videoCallCancel: "Cancelar",
      videoCallError: "Error en la videollamada. Intenta de nuevo.",
      videoCallEnded: "Llamada finalizada.",
      videoCallSpeakerView: "Vista orador",
      videoCallGridView: "Vista cuadrícula",
      videoCallCameraOn: "Encender cámara",
      videoCallCameraOff: "Apagar cámara",
      videoCallMicOn: "Encender micrófono",
      videoCallMute: "Silenciar",
      videoCallPeople: "Participantes",
      videoCallChat: "Chat",
      videoCallChatComingSoon: "Chat en la llamada próximamente.",
    },
    notifications: {
      title: "Notificaciones",
      defaultTitle: "Notificación",
      changeRequestTitle: "Cambio de cita – por confirmar",
      cancelledTitle: "Cita cancelada",
      cancelledBody: "El Dr. {doctorName} ha cancelado tu cita.",
      contactDoctorForRescheduling: "Contacta al médico para reprogramar.",
      dismiss: "Descartar",
      emptyTitle: "Sin notificaciones",
      emptyHint: "Aquí verás cambios en tus citas y avisos importantes.",
      approveChange: "Aprobar cambio",
      rejectChange: "Rechazar cambio",
      changeRejected: "Cambio rechazado. La cita fue cancelada.",
      chatWithDoctor: "Escribir al médico",
      communicateWithDoctor: "Puedes escribir al médico si tienes dudas.",
      approved: "Aprobada",
      appointmentConfirmed: "Cita confirmada",
      errorApprove:
        "No se pudo aprobar el cambio. Es posible que ya haya sido confirmada.",
      errorLoad: "Error al cargar notificaciones.",
    },
  },
  en: {
    speciality: {
      INT: "Internal Medicine",
      FAM: "Family and Community Medicine",
      PED: "Pediatrics",
      GYN: "Gynecology and Obstetrics",
      PSY: "Psychiatry",
      DER: "Dermatology",
      NEU: "Neurology",
      OPH: "Ophthalmology",
      ENT: "Otorhinolaryngology",
      ORT: "Traumatology and Orthopedics",
      SUR: "General Surgery",
      ANE: "Anesthesiology",
      ONC: "Medical Oncology",
      RAD: "Radiology / Diagnostic Imaging",
      EME: "Emergency Medicine",
      OCC: "Occupational Medicine",
      PMR: "Physical and Rehabilitation Medicine",
      PRE: "Preventive Medicine and Public Health",
      PSI: "Psychology",
      DEN: "Dentistry",
    },
    login: {
      title: "Log in",
      welcomeBack: "Welcome Back",
      accessYourAccount: "Access your account",
      welfareMessage:
        "Your health is our priority. Sign in to manage your appointments and connect with healthcare providers.",
      emailPlaceHolder: "Email",
      passwordPlaceHolder: "Password",
      logIn: "Log in",
      forgotPassword: "Forgot your password",
      noAccount: "Don't have an account? ",
      haveAccount: "Already have an account? ",
      createAccount: "Sign up",
      orDivider: "or",
      rememberMe: "Remember me",
      logInWithGoogle: "Log in with Google",
      logInWithApple: "Log in with Apple",
      country: "Country",
      countryName: "🇪🇨 Ecuador",
      language: "Language ",
      selectedLanguage: "English",
      emailRequired: "Please enter your email address.",
      passwordRequired: "Please enter your password.",
      invalidEmail: "The email format is not valid.",
      accountBlockedTitle: "Account blocked",
      accountBlockedMessage:
        "Your account has been blocked. Please contact support for more information.",
      understood: "Got it",
    },
    forgotPasswordRequest: {
      title: "Reset Password",
      subtitle: "Enter your email address",
      emailPlaceholder: "Email",
      sendCode: "Send Reset Code",
      sending: "Sending...",
      emailRequired: "Please enter your email address.",
      emailInvalid: "The email format is not valid.",
      errorTitle: "Error",
      successTitle: "Success",
      genericError: "An error occurred. Please try again.",
    },
    forgotPasswordReset: {
      title: "Reset Password",
      subtitle: "Fill in the fields below",
      codeSentTo: "A code was sent to: {email}",
      codePlaceholder: "Enter your reset code",
      passwordPlaceholder: "Enter your new password",
      passwordConfirmPlaceholder: "Confirm your new password",
      resetPassword: "Reset Password",
      resetting: "Resetting...",
      fieldsRequired: "Please fill in all fields.",
      passwordInvalid:
        "Password must be at least 8 characters with a number and a special character.",
      passwordMismatch: "Passwords do not match.",
      errorTitle: "Error",
      successTitle: "Success",
      successMessage: "Your password has been reset successfully.",
      genericError: "Could not reset password. Please try again.",
    },
    verifyEmail: {
      title: "Verify your email",
      subtitle: "Enter the 6-digit code we sent you",
      codeSentTo: "A code was sent to: {email}",
      codePlaceholder: "Verification code",
      verify: "Verify",
      resendCode: "Resend code",
      codeRequired: "Enter the code you received by email.",
      codeSent: "Code resent to your email.",
      success: "Email verified successfully.",
      genericError: "Could not verify the code. Please try again.",
      missingContext: "Missing information to verify your email. Please log in or sign up again.",
      goToLogin: "Go to login",
    },
    home: {
      search: "Search",
      findDoctor: "Find a doctor",
      dashHello: "Hello, {name}",
      dashHowAreYou: "How are you feeling today?",
      nextAppointment: "Next Appointment",
      noNextAppointment: "You have no appointments right now.",
      specialties: "Specialties",
      seeAll: "See all",
      favoriteDoctors: "Favorite Doctors",
      seeMore: "See more",
      allSpecialties: "All specialties",
      chipPediatrics: "Pediatrics",
      chipCardiology: "Cardiology",
      chipDentistry: "Dentistry",
      chipGeneral: "General Medicine",
      greetingHello: "Hello, {name}!",
      greetingMessage: "Your health is our priority.",
      titleOne: "Your Health is",
      titleTwo: "our priority",
      suggestion:
        '"Sleeping well, eating well, and breathing deeply is also productivity."',
      upcomingAppointments: "Upcoming appointments",
      seeAllAppointments: "See all appointments",
      noUpcoming: "You have no upcoming appointments.",
      welfareTips: [
        '"Sleeping well, eating well, and breathing deeply is also productivity."',
        '"Small daily steps improve your long-term wellbeing."',
        '"Your mental health is as important as your physical health."',
        '"Staying hydrated is one of the best habits you can have."',
        '"A short walk each day can change how you feel."',
      ],
    },
    findDoctor: {
      title: "Find a doctor",
      subtitle: "Choose a specialty",
      seeDoctors: "See doctors",
      noDoctors: "No doctors in this specialty",
      tryAnother: "Try another specialty",
      errorLoading: "Error loading. Please try again.",
      doctorCount: "doctor",
      doctorCountPlural: "doctors",
    },
    signupUser: {
      createAccountTitle1: "Create a\n",
      createAccountTitle2: "new account",
      name: "NAME",
      firstName: "FIRST NAME(S)",
      firstNamePlaceholder: "E.g. Juan",
      firstNameRequired: "Please enter your first name.",
      lastName: "LAST NAME(S)",
      lastNamePlaceholder: "E.g. Smith",
      lastNameRequired: "Please enter your last name.",
      nationalId: "NATIONAL ID",
      nationality: "NATIONALITY",
      nationalityPlaceholder: "Select your nationality",
      nationalityRequired: "Please select your nationality",
      birthDate: "DATE OF BIRTH",
      phone: "PHONE",
      province: "PROVINCE",
      street: "STREET",
      email: "EMAIL",
      password: "PASSWORD",
      passwordPlaceholder: "Ex: 1234@Abc",
      confirmPassword: "CONFIRM PASSWORD",
      createAccountButton: "Create account",
      emailInvalid: "Invalid email",
      passwordInvalid:
        "Password must be at least 8 characters, with uppercase, lowercase, number, and symbol",
      passwordMismatch: "Passwords do not match",
      phoneInvalid: "Invalid phone number",
      nationalIdInvalid: "Invalid ID",
      birthDateInvalid: "Date must be in the past",
      error1: "Registration error",
      namePlaceholder: "Ex: John Smith",
      phonePlaceholder: "0999999999",
      nationalIDPlaceholder: "1234567890",
      cancel: "Cancel",
      ok: "Ok",
      done: "Done",
      streetPlaceholder: "Ex: Machala and Salinas",
      emailPlaceholder: "Ex: example@gmail.com",
      emailDuplicate:
        "A user with the email: {VAL} is already in use, please try resetting your password",
      idDuplicate: "A user with the ID {VAL} is already in use",
      errorFromDb: "An error has occurred, please try again",
    },
    doctorSearch: {
      searchLabel: "Name, Specialty",
      seachPlaceholder: "Search",
      SearchQueryIsRequired: "Search query is required",
      errorOcured: "An error occurred, please try again",
      filtersTitle: "Filters",
      province: "Province",
      noDataFound: "No results found",
      cleanFiltersTitle: "Clear filters",
      offices: "Offices",
    },
    doctorProfile: {
      bookAppointment: "Book Appointment",
      selectLocation: "Select a clinic:",
      phone: "Phone:",
      email: "Email:",
      schedule: "Schedule",
      languages: "Languages",
      paymentMethod: "Payment Methods",
      insurance: "Insurance Companies",
      noInsurances: "No insurances listed.",
      insurancePlan: "Plan",
      insurancePolicyNumber: "Policy number",
      insuranceWebsite: "Website",
      profile: "Professional Profile",
      location: "Location",
      selectLocationAlert: "Please select a clinic",
      morning: "Morning",
      afternoon: "Afternoon",
      fullDay: "Full Day",
      errorLoadingData:
        "An error occurred while loading the data, please try again",
      errorBooking: "An error occurred, please try again",
      seeLocation: "See location",
      clinics: "Clinics",
    },
    appointments: {
      myAppointments: "My Appointments",
      nextAppointments: "Upcoming Appointments",
      pastAppointments: "Past Appointments",
      name: "Name:",
      speciality: "Specialty:",
      date: "Date:",
      time: "Time:",
      location: "Place:",
      status: "Status:",
      dateError:
        "Appointments can only be canceled through this method up to 12h before. After that, contact the doctor directly.",
      cancelAppointment: "Cancel Appointment",
      bookAgain: "Book Again",
      messageDoctor: "Message doctor",
      cancelationMessage: "Are you sure you want to cancel this appointment?",
      cancelReasonPlaceholder: "Cancellation reason (optional)",
      cancellationReasonLabel: "Cancellation reason",
      confirmButton: "Confirm",
      closeButton: "Cancel",
      closeModal: "Close",
      viewDetails: "View details",
      detailsTitle: "Appointment Details",
      appointmentInfo: "Appointment Information",
      consultationType: "Consultation Type",
      consultationMode: "Consultation Mode",
      modeInPerson: "In-person",
      modeVideo: "Video call",
      reschedule: "Reschedule",
      scheduled: {
        cero: "Scheduled",
        uno: "Completed",
      },
      pending: {
        cero: "Pending confirmation",
        uno: "Pending confirmation",
      },
      rescheduled: {
        cero: "Rescheduled",
        uno: "Rescheduled",
      },
      cancelled: {
        cero: "Canceled",
        uno: "Canceled",
      },
      bookNewAppointment: "Book appointment",
      cancel: "Cancel",
      noCurrent: "You have no booked appointments",
      noPasst: "You have no past appointments",
      timeRemainingDays: "{count} days",
      timeRemainingDay: "1 day",
      timeRemainingToday: "Today",
      timeRemainingTomorrow: "Tomorrow",
    },
    account: {
      myProfile: "My Profile",
      editProfile: "Edit Profile",
      resetPassword: "Reset Password",
      language: "Language",
      selectedLanguage: "English",
      logOut: "Log Out",
      confirmLogOut: "Are you sure?",
      languageSelect: "Select your language",
      closeButton: "Cancel",
    },
    bookAppointment: {
      noSlots: "No available slots for this date",
      waitlistNotify: "Notify me if a slot opens up",
      waitlistJoined: "We'll notify you when a slot opens up",
      waitlistJoining: "Joining...",
      selectClinic: "Select a clinic",
      selectDate: "Select a date",
      selectType: "Select appointment type",
      timeSlots: "Available times",
      confirmAppointment: "Confirm Appointment",
      errorDataDates: "Error loading dates",
      noAvailableDates: "No available dates",
      errorDataTimes: "Error loading times",
      searchPlaceholder: "Search by name or specialty",
      selectDoctor: "Select a doctor",
      morning: "Morning",
      afternoon: "Afternoon",
      noResults: "No results",
      clearSearch: "Clear search",
      changeHour: "Change hour",
      bookingSuccess: "Appointment booked successfully",
      bookingError: "Could not book appointment",
      createAppointmentWithDoctor: "Book Appointment",
    },
    daysOfWeek: [
      "Sunday",
      "Monday",
      "Tuesday",
      "Wednesday",
      "Thursday",
      "Friday",
      "Saturday",
    ],
    months: [
      "January",
      "February",
      "March",
      "April",
      "May",
      "June",
      "July",
      "August",
      "September",
      "October",
      "November",
      "December",
    ],
    myProfile: {
      emailInvalid: "Invalid email",
      phoneInvalid: "Invalid phone number",
      nationalIdInvalid: "Invalid ID number",
      oldPasswordInvalid: "Current password required",
      passwordInvalid:
        "Password must be at least 8 characters, with uppercase, lowercase, number, and symbol",
      passwordMismatch: "Passwords do not match",
      deleteCategory: "Delete Category",
      eliminar: "Delete",
      addCondition: "Add medical condition",
      selectCategory: "Select a category",
      conditionPlaceholder: "Medical condition",
      addVaccine: "Add vaccine",
      vaccineNamePlaceholder: "Vaccine name",
      date: "Date",
      SelectDate: "Select the vaccine date",
      details: "Personal details",
      province: "Province",
      country: "Country",
      height: "Height (cm)",
      weight: "Weight (kg)",
      bloodType: "Blood type",
      bloodTypeSelect: "Select your blood type",
      gender: "Gender",
      genderMale: "Male",
      genderFemale: "Female",
      genderDiverse: "Diverse",
      city: "City",
      parish: "Parish",
      languages: "Languages you speak",
      languagesOptional: "Optional",
      emergencyContact: "Emergency contact",
      emergencyContactName: "Contact name",
      emergencyContactPhone: "Contact phone",
      emergencyContactRelationship: "Relationship (e.g. mother, spouse)",
      medicationReminders: "Medication reminders",
      medicationNamePlaceholder: "Medication name",
      medicationDosePlaceholder: "Dose (optional)",
      medicationTime: "Reminder time",
      medicationReminderToggle: "Remind me with an alarm",
      addMedication: "Add medication",
      noMedicationReminders: "No medications with reminders added",
      vaccineReminderToggle: "Remind me for the next dose",
      vaccineReminderDate: "Reminder date",
      editYourProfile: "Edit your profile",
      medicalConditions: "Medical conditions",
      vaccines: "Vaccines",
      save: "Save changes",
      oldPassword: "Current password",
      newPassword: "New password",
      newPasswordConfirm: "Confirm new password",
      savePassword: "Save new password",
      sendCode: "Send confirmation code",
      codeSent: "Confirmation code sent to your email.",
      codeSentMessage: "Enter the confirmation code we sent to your email.",
      confirmationCode: "Confirmation code",
      codeRequired: "Enter the code you received by email.",
      cancel: "Cancel",
      changePassword: "Change password",
      closeAccount: "Delete account",
      name: "Name",
      firstName: "First name(s)",
      firstNameRequired: "Please enter your first name.",
      lastName: "Last name(s)",
      lastNameRequired: "Please enter your last name.",
      email: "E-Mail",
      phone: "Phone",
      address: "Adrress",
      close: "Done",
      banerSuccess: "Data succesfuly updated",
      banerError: "There was an error updating",
      noCondition: "No medical conditions added, please add one",
      noVaccine: "No vaccines added, please add one",
      banerErrorGetUser: "There was an error getting user data",
      document: "Document",
      healthInfo: "Health Information",
      noDisponible: "Not available",
      scheduleVideoCall: "Schedule video call",
      clinicalHistory: "Clinical History",
      medications: "Medications",
      allergies: "Allergies",
      allergyCountOne: "1 allergy",
      allergyCountOther: "{{count}} allergies",
      vaccineCountOne: "1 vaccine",
      vaccineCountOther: "{{count}} vaccines",
      editProfile: "Edit personal details",
      accountSettings: "Account",
      informationSection: "Information",
      dateOfBirth: "Date of birth",
      profileTitle: "Profile",
      noRegistrado: "Not recorded",
      editShort: "Edit",
      sectionPhysical: "Physical data",
      sectionMedicalHistory: "Medical history",
      sectionAccess: "Quick access",
      favoriteDoctors: "Favorite doctors",
      waitlist: "Waitlist",
      allergyAddPlaceholder: "e.g. Penicillin",
      add: "Add",
      noAllergies: "No allergies added",
    },
    medicalCategories: [
      { label: "Infectious Diseases", value: "IFDI" },
      { label: "Cardiovascular Diseases", value: "CVDI" },
      { label: "Respiratory Diseases", value: "RSDI" },
      { label: "Neurological Disorders", value: "NEDI" },
      { label: "Mental Health Disorders", value: "MHDI" },
      { label: "Endocrine and Metabolic Disorders", value: "EMDI" },
      { label: "Musculoskeletal Disorders", value: "MSDI" },
      { label: "Gastrointestinal Disorders", value: "GIDI" },
      { label: "Genetic and Congenital Disorders", value: "GCDI" },
      { label: "Cancers (Oncological Diseases)", value: "ONCO" },
      { label: "Dermatological Conditions", value: "DERM" },
      { label: "Renal and Urological Disorders", value: "RUDI" },
      { label: "Hematologic Disorders (Blood)", value: "HEMD" },
      { label: "Reproductive Health Disorders", value: "RHDI" },
      { label: "Immune System Disorders", value: "IMMU" },
      { label: "Ocular Disorders (Ophthalmology)", value: "OPHT" },
      { label: "Ear, Nose, and Throat Disorders (ENT)", value: "ENTI" },
      { label: "Nutritional Deficiencies", value: "NUDI" },
      { label: "Pain Disorders", value: "PAIN" },
      { label: "Toxicological Conditions", value: "TOXI" },
    ],
    medicalCategoryValues: {
      IFDI: "Infectious Diseases",
      CVDI: "Cardiovascular Diseases",
      RSDI: "Respiratory Diseases",
      NEDI: "Neurological Disorders",
      MHDI: "Mental Health Disorders",
      EMDI: "Endocrine and Metabolic Disorders",
      MSDI: "Musculoskeletal Disorders",
      GIDI: "Gastrointestinal Disorders",
      GCDI: "Genetic and Congenital Disorders",
      ONCO: "Cancers (Oncological Diseases)",
      DERM: "Dermatological Conditions",
      RUDI: "Renal and Urological Disorders",
      HEMD: "Hematologic Disorders (Blood)",
      RHDI: "Reproductive Health Disorders",
      IMMU: "Immune System Disorders",
      OPHT: "Ocular Disorders (Ophthalmology)",
      ENTI: "Ear, Nose, and Throat Disorders (ENT)",
      NUDI: "Nutritional Deficiencies",
      PAIN: "Pain Disorders",
      TOXI: "Toxicological Conditions",
    },
    maps: {
      openGoogleMaps: "Open with Google Maps",
      openWays: "Open with Waze",
      openAppleMaps: "Open with Apple Maps",
      cencel: "Cancel",
    },
    messages: {
      title: "Messages",
      consultation: "Consultation",
      available: "Available",
      timeAgoMin: "{{n}} min ago",
      timeAgoHour: "{{n}} h ago",
      timeAgoDay: "{{n}} days ago",
      noMessages: "No messages",
      placeholder: "Messages will be available soon.",
      emptyConversations: "You have no conversations yet.",
      emptyConversationsHint:
        "Open an appointment and tap «Message doctor» to start a conversation.",
      typeMessage: "Type a message...",
      send: "Send",
      loading: "Loading...",
      errorLoad: "Error loading.",
      errorConversation: "Could not open conversation.",
      videoCall: "Video call",
      joinVideoCallTitle: "Join video call",
      videoCallCodePlaceholder: "Room code",
      join: "Join",
      videoCallCodeRequired: "Enter the room code.",
      videoCallJoinSuccess:
        "Valid code. Joining the call will be implemented next.",
      videoCallRoomNotFound: "Room not found or invalid code.",
      videoCallRoomExpired: "The room has expired.",
      videoCallTooEarly: "Available 5 min before",
      videoCallEnded: "Call ended",
      videoCallConnecting: "Connecting...",
      videoCallLeave: "Leave call",
      videoCallLeaveTitle: "Leave call",
      videoCallLeaveMessage: "Are you sure you want to leave?",
      videoCallLeaveConfirm: "Leave",
      videoCallCancel: "Cancel",
      videoCallError: "Video call error. Please try again.",
      videoCallEnded: "Call ended.",
      videoCallSpeakerView: "Speaker view",
      videoCallGridView: "Grid view",
      videoCallCameraOn: "Turn on camera",
      videoCallCameraOff: "Turn off camera",
      videoCallMicOn: "Unmute",
      videoCallMute: "Mute",
      videoCallPeople: "People",
      videoCallChat: "Chat",
      videoCallChatComingSoon: "In-call chat coming soon.",
    },
    notifications: {
      title: "Notifications",
      defaultTitle: "Notification",
      changeRequestTitle: "Appointment change – please confirm",
      cancelledTitle: "Appointment cancelled",
      cancelledBody: "Dr. {doctorName} has cancelled your appointment.",
      contactDoctorForRescheduling: "Contact the doctor for rescheduling.",
      dismiss: "Dismiss",
      emptyTitle: "No notifications",
      emptyHint: "You'll see appointment changes and important alerts here.",
      approveChange: "Approve change",
      rejectChange: "Reject change",
      changeRejected: "Change rejected. The appointment was cancelled.",
      chatWithDoctor: "Chat with doctor",
      communicateWithDoctor:
        "You can message the doctor if you have questions.",
      approved: "Approved",
      appointmentConfirmed: "Appointment confirmed",
      errorApprove:
        "Could not approve the change. It may have already been confirmed.",
      errorLoad: "Error loading notifications.",
    },
  },
};

export default STRINGS;
