import { Dimensions, StyleSheet } from "react-native";
import {
  COLORS,
  FONT_WEIGHT,
  FONT_FAMILY,
  VALUES,
  FONT_SIZES,
  PADDINGS,
  getShadowStyle,
  getGlassShadow,
  getGlassStyle,
} from "../../../styles/theme";

const screenWidth = Dimensions.get("window").width;

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  mainElementContainer: {
    paddingTop: 50,
  },
  elementContainer: {
    marginHorizontal: PADDINGS.screenEdge,
  },
  flatlistElement: { marginBottom: 95 },
  title: {
    fontWeight: FONT_WEIGHT.boldFontBig,
    fontSize: FONT_SIZES.sectionTitleBig,
    marginBottom: PADDINGS.screenEdge,
    fontFamily: FONT_FAMILY.semiBold,
  },
  tabRowCard: {
    flexDirection: "row",
    marginBottom: PADDINGS.screenEdge,
    justifyContent: "space-around",
    backgroundColor: "rgba(255, 255, 255, 0.92)",
    borderRadius: 16,
    paddingVertical: 10,
    paddingHorizontal: 16,
    ...getGlassShadow({ y: 2, blur: 6, opacity: 0.08, elevation: 3 }),
  },
  tabRow: {
    flexDirection: "row",
    flex: 1,
    justifyContent: "space-around",
  },
  tab: {
    flex: 1,
    alignItems: "center",
  },
  tabText: {
    color: COLORS.blackText,
    fontSize: FONT_SIZES.subtitle2,
    fontFamily: FONT_FAMILY.regular,
  },
  activeTabText: {
    fontWeight: FONT_WEIGHT.boldFont,
    color: COLORS.secondary,
    fontFamily: FONT_FAMILY.semiBold,
    fontSize: FONT_SIZES.subtitle2,
  },
  tabSecondary: {
    flex: 1,
    alignItems: "center",
  },
  tabTextSecondary: {
    color: COLORS.greyText,
    fontSize: FONT_SIZES.subtitle2,
    fontFamily: FONT_FAMILY.regular,
  },
  activeTabTextSecondary: {
    color: COLORS.secondary,
    fontFamily: FONT_FAMILY.semiBold,
    fontSize: FONT_SIZES.subtitle2,
  },
  underlineSecondary: {
    marginTop: 4,
    height: 2,
    width: "80%",
    backgroundColor: COLORS.secondary,
    borderRadius: 2,
    opacity: 0.9,
  },
  underline: {
    marginTop: 4,
    height: 3,
    width: "80%",
    backgroundColor: COLORS.secondary,
    borderRadius: 2,
  },
  cardItem: {
    backgroundColor: COLORS.cardItemBackground,
    width: screenWidth - 40,
    marginBottom: 16,
    padding: 16,
    borderRadius: 16,
    ...getShadowStyle({ y: 4, blur: 6, opacity: 0.1, elevation: 5 }),
    marginHorizontal: PADDINGS.screenEdge,
  },
  cardHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  cardDoctorBlock: {
    flex: 1,
    marginLeft: 12,
  },
  cardDoctorName: {
    fontWeight: FONT_WEIGHT.boldFont,
    fontSize: FONT_SIZES.subtitle2,
    fontFamily: FONT_FAMILY.semiBold,
    color: COLORS.blackText,
  },
  cardSpecialty: {
    fontSize: FONT_SIZES.xsText,
    color: COLORS.greyText,
    fontFamily: FONT_FAMILY.regular,
    marginTop: 2,
  },
  statusPill: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 20,
    backgroundColor: "rgba(76, 175, 80, 0.15)",
  },
  statusPillCancelled: {
    backgroundColor: "rgba(244, 67, 54, 0.12)",
  },
  statusPillText: {
    fontSize: FONT_SIZES.xsText,
    color: COLORS.green,
    fontFamily: FONT_FAMILY.semiBold,
  },
  statusPillTextCancelled: {
    color: COLORS.error,
  },
  // S10: amber for "Pendiente de confirmación", blue for "Reprogramada".
  statusPillPending: {
    backgroundColor: "rgba(245, 158, 11, 0.15)",
  },
  statusPillTextPending: {
    color: "#B45309",
  },
  statusPillRescheduled: {
    backgroundColor: "rgba(37, 99, 235, 0.12)",
  },
  statusPillTextRescheduled: {
    color: "#1D4ED8",
  },
  cardDateRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 6,
    marginLeft: 68,
  },
  cardTimeRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 4,
    marginLeft: 68,
  },
  cardDetailIcon: {
    marginRight: 8,
  },
  cardDetailText: {
    fontSize: FONT_SIZES.inputText,
    color: COLORS.blackText,
    fontFamily: FONT_FAMILY.regular,
  },
  cardActionsRow: {
    flexDirection: "row",
    marginTop: 12,
    gap: 8,
  },
  buttonVerDetalles: {
    ...getGlassStyle("secondary"),
    flex: 1,
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  buttonVerDetallesText: {
    fontSize: FONT_SIZES.xsText,
    color: COLORS.secondary,
    fontFamily: FONT_FAMILY.semiBold,
  },
  buttonCancelar: {
    ...getGlassStyle("danger"),
    flex: 1,
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  buttonCancelarDisabled: {
    borderColor: COLORS.greyBorder,
  },
  buttonCancelarText: {
    fontSize: FONT_SIZES.xsText,
    color: COLORS.error,
    fontFamily: FONT_FAMILY.semiBold,
  },
  buttonCancelarTextDisabled: {
    color: COLORS.greyText,
  },
  cardIcon: {
    width: 40,
    height: 40,
    marginRight: PADDINGS.screenEdge,
    marginLeft: 5,
  },
  item1: {
    fontWeight: FONT_WEIGHT.boldFont,
    fontSize: FONT_SIZES.subtitle2,
    fontFamily: FONT_FAMILY.regular,
  },
  modalOverlay: {
    flex: 1,
    justifyContent: "flex-end",
    backgroundColor: "rgba(0,0,0,0.48)",
  },
  modalContent: {
    marginHorizontal: PADDINGS.screenEdge,
    marginBottom: 28,
    borderRadius: 24,
    backgroundColor: COLORS.white,
    paddingTop: 16,
    paddingHorizontal: PADDINGS.screenEdge,
    paddingBottom: PADDINGS.screenEdge,
    ...getShadowStyle({ y: -4, blur: 16, opacity: 0.12, elevation: 12 }),
    maxHeight: "85%",
  },
  modalSheetHandle: {
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: COLORS.greyBorder,
    alignSelf: "center",
    marginBottom: 12,
  },
  modalScroll: {
    maxHeight: 360,
  },
  doctorName: {
    fontSize: FONT_SIZES.sectionTitleBig,
    fontWeight: FONT_WEIGHT.boldFontBig,
    marginBottom: 12,
    fontFamily: FONT_FAMILY.bold,
    color: COLORS.blackText,
  },
  modalRow: {
    marginBottom: 10,
  },
  modalLabel: {
    fontSize: FONT_SIZES.xsText,
    fontWeight: FONT_WEIGHT.boldFont,
    color: COLORS.greyText,
    marginBottom: 2,
    fontFamily: FONT_FAMILY.semiBold,
  },
  modalValue: {
    fontSize: FONT_SIZES.inputText,
    fontWeight: FONT_WEIGHT.medium,
    color: COLORS.blackText,
    fontFamily: FONT_FAMILY.regular,
  },
  modalLink: {
    color: COLORS.blackText,
    textDecorationLine: "underline",
  },
  modalStatus: {
    color: COLORS.blackText,
  },
  modalStatusCancelled: {
    color: COLORS.greyText,
  },
  modalDateRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 10,
    flexWrap: "wrap",
  },
  modalDateValueWrap: {
    flex: 1,
  },
  cancelAppointmentTextBtn: {
    paddingVertical: 4,
    paddingHorizontal: 0,
  },
  cancelAppointmentTextBtnText: {
    fontSize: FONT_SIZES.xsText,
    color: COLORS.error,
    fontFamily: FONT_FAMILY.semiBold,
    textDecorationLine: "underline",
  },
  modalButtons: {
    marginTop: 16,
  },
  typeButton: {
    ...getGlassStyle("primary"),
    paddingVertical: 12,
    paddingHorizontal: PADDINGS.mediumButtonHorizontal,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    marginBottom: 10,
  },
  typeButtonSecondary: {
    ...getGlassStyle("secondary"),
  },
  typeButtonText: {
    fontWeight: FONT_WEIGHT.boldFont,
    color: COLORS.selectedItem,
    fontSize: FONT_SIZES.mediumButtonText,
    fontFamily: FONT_FAMILY.regular,
  },
  typeButtonTextSecondary: {
    color: COLORS.secondary,
  },
  closeButton: {
    ...getGlassStyle("primary"),
    marginTop: 16,
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
  },
  closeButtonText: {
    fontWeight: FONT_WEIGHT.boldFont,
    color: COLORS.selectedItem,
    fontSize: FONT_SIZES.mediumButtonText,
    fontFamily: FONT_FAMILY.regular,
  },
  buttonInactive: {
    opacity: VALUES.inactiveButtonOpacity,
  },
  itemTextConteiner: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
  },
  bold: {
    fontWeight: FONT_WEIGHT.boldFont,
    fontFamily: FONT_FAMILY.regular,
  },
  newAppointmentButton: {
    ...getGlassStyle("primary"),
    position: "absolute",
    bottom: 30,
    zIndex: 10,
    right: PADDINGS.screenEdge,
    paddingVertical: PADDINGS.mainButtonVertical,
    paddingHorizontal: PADDINGS.mainButtonHorizontal,
    borderRadius: 20,
  },
  newAppointmentButtonText: {
    color: COLORS.selectedItem,
    fontWeight: FONT_WEIGHT.boldFont,
    fontSize: FONT_SIZES.mediumButtonText,
    fontFamily: FONT_FAMILY.regular,
  },
  linkElement: { color: COLORS.externalLink },
  active: { color: COLORS.green },
  inActive: { color: COLORS.error },
  avatar: {
    width: 56,
    height: 56,
    borderRadius: 28,
  },
  avatarPlaceholder: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: COLORS.secondary,
    alignItems: "center",
    justifyContent: "center",
  },
  avatarInitials: {
    color: COLORS.whiteText,
    fontSize: FONT_SIZES.subtitle2,
    fontWeight: FONT_WEIGHT.boldFont,
    fontFamily: FONT_FAMILY.semiBold,
  },
  statusTagContainer: {
    flex: 1,
    position: "relative",
  },
  statusTagText: {
    position: "absolute",
    top: 0,
    right: 0,
    fontWeight: "bold",
    fontFamily: FONT_FAMILY.regular,
  },
  noDataContainer: {
    flex: 1,
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: PADDINGS.screenEdge,
    // Pull the empty-state up toward the tabs (~half the previous top gap).
    marginTop: -160,
  },
  nodataImage: {
    width: "80%",
    maxHeight: 300,
    alignSelf: "center",
    marginBottom: PADDINGS.screenEdge,
  },
  loaderContainer: {
    paddingTop: 30,
    transform: [{ scale: 2 }],
  },

  /* ---- Redesigned full-screen appointment detail (mockup) ---- */
  detailHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingBottom: 10,
  },
  detailBackBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "rgba(255,255,255,0.3)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.6)",
    alignItems: "center",
    justifyContent: "center",
    ...getGlassShadow({ y: 2, blur: 8, opacity: 0.08 }),
  },
  detailHeaderTitle: {
    flex: 1,
    textAlign: "center",
    fontSize: FONT_SIZES.sectionTitleBig,
    fontWeight: FONT_WEIGHT.boldFontBig,
    color: COLORS.blackText,
    fontFamily: FONT_FAMILY.semiBold,
  },
  detailScroll: {
    flex: 1,
    paddingHorizontal: 16,
  },
  detailDoctorCard: {
    backgroundColor: COLORS.cardItemBackground,
    borderRadius: 16,
    paddingTop: 22,
    paddingBottom: 20,
    paddingHorizontal: 16,
    alignItems: "center",
    marginTop: 6,
    ...getShadowStyle({ y: 2, blur: 8, opacity: 0.06, elevation: 2 }),
  },
  detailStatusPill: {
    position: "absolute",
    top: 14,
    right: 14,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 20,
    backgroundColor: "rgba(37, 99, 235, 0.12)",
  },
  detailStatusPillText: {
    fontSize: FONT_SIZES.xsText,
    color: COLORS.selectedItem,
    fontFamily: FONT_FAMILY.semiBold,
    marginLeft: 4,
  },
  detailAvatar: {
    width: 110,
    height: 110,
    borderRadius: 55,
    borderWidth: 4,
    borderColor: COLORS.white,
  },
  detailAvatarPlaceholder: {
    width: 110,
    height: 110,
    borderRadius: 55,
    borderWidth: 4,
    borderColor: COLORS.white,
    backgroundColor: COLORS.secondary,
    alignItems: "center",
    justifyContent: "center",
  },
  detailAvatarInitials: {
    fontSize: 34,
    color: COLORS.white,
    fontFamily: FONT_FAMILY.bold,
  },
  detailDoctorName: {
    marginTop: 14,
    fontSize: FONT_SIZES.subtitle2,
    fontWeight: FONT_WEIGHT.boldFont,
    color: COLORS.blackText,
    fontFamily: FONT_FAMILY.semiBold,
    textAlign: "center",
  },
  detailSpecialtyChip: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 10,
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 20,
    backgroundColor: "#F1F5F9",
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.06)",
  },
  detailSpecialtyChipIcon: {
    width: 22,
    height: 22,
    borderRadius: 11,
  },
  detailSpecialtyChipText: {
    marginLeft: 7,
    fontSize: FONT_SIZES.inputText,
    color: COLORS.blackText,
    fontFamily: FONT_FAMILY.semiBold,
  },
  detailActionIconsRow: {
    flexDirection: "row",
    marginTop: 16,
    gap: 18,
  },
  detailActionIcon: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: "rgba(255,255,255,0.28)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.6)",
    alignItems: "center",
    justifyContent: "center",
    ...getGlassShadow({ y: 2, blur: 8, opacity: 0.08 }),
  },
  detailSectionTitle: {
    marginTop: 24,
    marginBottom: 12,
    fontSize: FONT_SIZES.inputTitle,
    color: COLORS.blackText,
    fontWeight: FONT_WEIGHT.boldFontBig,
    fontFamily: FONT_FAMILY.bold,
    letterSpacing: 0.5,
  },
  detailHalfRow: {
    flexDirection: "row",
    gap: 12,
  },
  detailHalfCard: {
    flex: 1,
    backgroundColor: COLORS.cardItemBackground,
    borderRadius: 16,
    paddingVertical: 16,
    paddingHorizontal: 16,
    ...getShadowStyle({ y: 2, blur: 8, opacity: 0.06, elevation: 2 }),
  },
  detailHalfAccent: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    width: 4,
    backgroundColor: COLORS.selectedItem,
  },
  detailCardIconCircle: {
    width: 30,
    height: 30,
    alignItems: "center",
    justifyContent: "flex-start",
    marginBottom: 10,
  },
  detailCardLabel: {
    fontSize: FONT_SIZES.inputText,
    color: COLORS.blackText,
    fontWeight: FONT_WEIGHT.boldFont,
    fontFamily: FONT_FAMILY.bold,
    marginBottom: 4,
  },
  detailCardValue: {
    fontSize: FONT_SIZES.inputText,
    color: COLORS.blackText,
    fontFamily: FONT_FAMILY.regular,
  },
  detailInfoRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.cardItemBackground,
    borderRadius: 16,
    paddingVertical: 14,
    paddingHorizontal: 14,
    marginTop: 12,
    ...getShadowStyle({ y: 2, blur: 8, opacity: 0.06, elevation: 2 }),
  },
  detailInfoIconCircle: {
    width: 34,
    height: 34,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  detailInfoTextWrap: {
    flex: 1,
  },
  detailInfoLabel: {
    fontSize: FONT_SIZES.inputText,
    color: COLORS.blackText,
    fontWeight: FONT_WEIGHT.boldFont,
    fontFamily: FONT_FAMILY.bold,
    marginBottom: 3,
  },
  detailInfoValue: {
    fontSize: FONT_SIZES.inputText,
    color: COLORS.blackText,
    fontFamily: FONT_FAMILY.regular,
  },
  detailBottomBar: {
    flexDirection: "row",
    gap: 12,
    paddingHorizontal: 16,
    paddingTop: 10,
  },
  detailBtn: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    borderWidth: 1,
    ...getGlassShadow({ y: 2, blur: 10, opacity: 0.1 }),
  },
  detailBtnPrimary: {
    backgroundColor: "rgba(255,255,255,0.28)",
    borderColor: "rgba(37, 99, 235, 0.55)",
  },
  detailBtnPrimaryText: {
    fontSize: FONT_SIZES.textButton,
    color: COLORS.selectedItem,
    fontFamily: FONT_FAMILY.bold,
  },
  detailBtnSecondary: {
    backgroundColor: "rgba(255,255,255,0.28)",
    borderColor: "rgba(37, 99, 235, 0.55)",
  },
  detailBtnSecondaryText: {
    fontSize: FONT_SIZES.textButton,
    color: COLORS.selectedItem,
    fontFamily: FONT_FAMILY.bold,
  },
  detailBtnDanger: {
    backgroundColor: "rgba(255,255,255,0.28)",
    borderColor: "rgba(255, 0, 0, 0.5)",
  },
  detailBtnDangerText: {
    fontSize: FONT_SIZES.textButton,
    color: COLORS.error,
    fontFamily: FONT_FAMILY.bold,
  },
  detailBtnDisabled: {
    opacity: 0.5,
  },
  detailReasonInput: {
    borderWidth: 1,
    borderColor: COLORS.greyBorder,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    minHeight: 60,
    color: COLORS.blackText,
    textAlignVertical: "top",
    backgroundColor: "rgba(255,255,255,0.9)",
    marginHorizontal: 16,
    marginTop: 8,
    fontFamily: FONT_FAMILY.regular,
  },
});

export default styles;
