import { StyleSheet, Platform } from "react-native";
import {
  COLORS,
  FONT_SIZES,
  FONT_WEIGHT,
  FONT_FAMILY,
  PADDINGS,
  getShadowStyle,
  getGlassShadow,
  getGlassStyle,
} from "../../../styles/theme";

const CARD_RADIUS = 12;
const INPUT_RADIUS = 10;

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.screenBackground,
  },
  scroll: {
    flex: 1,
    paddingHorizontal: PADDINGS.screenEdge,
    paddingTop: Platform.OS === "web" ? 24 : 60,
  },
  // Bottom padding belongs on the scroll CONTENT so the last item (the confirm
  // button) can scroll clear of the merged bottom tab/search bar — extra room
  // for Android's taller bar + gesture nav.
  scrollContent: {
    paddingBottom: PADDINGS.tabBarSafeBottom + 48,
  },
  backRow: {
    marginBottom: 16,
  },
  searchWrap: {
    position: "relative",
    zIndex: 10,
  },
  searchInput: {
    backgroundColor: COLORS.white,
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderRadius: INPUT_RADIUS,
    fontSize: FONT_SIZES.inputText,
    color: COLORS.blackText,
    borderWidth: 1,
    borderColor: COLORS.greyBorder,
    fontFamily: FONT_FAMILY.regular,
  },
  guestInput: {
    backgroundColor: COLORS.white,
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderRadius: INPUT_RADIUS,
    fontSize: FONT_SIZES.inputText,
    color: COLORS.blackText,
    borderWidth: 1,
    borderColor: COLORS.greyBorder,
    fontFamily: FONT_FAMILY.regular,
    marginTop: 10,
  },
  dropdown: {
    position: "absolute",
    left: 0,
    right: 0,
    top: "100%",
    marginTop: 4,
    backgroundColor: COLORS.white,
    borderRadius: INPUT_RADIUS,
    borderWidth: 1,
    borderColor: COLORS.greyBorder,
    maxHeight: 600,
    ...getShadowStyle({ y: 2, blur: 8, opacity: 0.1, elevation: 6 }),
  },
  dropdownItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(0,0,0,0.06)",
  },
  dropdownItemText: {
    flex: 1,
    fontSize: FONT_SIZES.inputText,
    color: COLORS.blackText,
  },
  dropdownItemSub: {
    fontSize: FONT_SIZES.xsText,
    color: COLORS.greyText,
    marginTop: 2,
  },

  // ── Rich search-result cards ────────────────────────────────────────────────
  resultsScroll: {
    maxHeight: 560,
  },
  resultCard: {
    flexDirection: "row",
    backgroundColor: COLORS.white,
    borderRadius: CARD_RADIUS,
    marginHorizontal: 8,
    marginVertical: 6,
    overflow: "hidden",
    ...getShadowStyle({ y: 1, blur: 6, opacity: 0.08, elevation: 3 }),
  },
  resultAccent: {
    width: 4,
  },
  resultBody: {
    flex: 1,
    padding: 12,
  },
  resultTopRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  resultAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: COLORS.greyBorder,
  },
  resultAvatarPlaceholder: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.secondary,
  },
  resultAvatarInitials: {
    fontSize: FONT_SIZES.generalText,
    fontWeight: FONT_WEIGHT.bold,
    color: COLORS.whiteText,
  },
  resultName: {
    fontSize: FONT_SIZES.inputTitle,
    fontWeight: FONT_WEIGHT.bold,
    color: COLORS.blackText,
  },
  resultChip: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    gap: 4,
    marginTop: 4,
    paddingVertical: 3,
    paddingHorizontal: 8,
    borderRadius: 999,
    backgroundColor: "rgba(112, 193, 227, 0.15)",
  },
  resultChipIcon: {
    width: 16,
    height: 16,
    borderRadius: 4,
  },
  resultChipText: {
    fontSize: FONT_SIZES.xsText,
    color: COLORS.blackText,
    fontWeight: FONT_WEIGHT.medium,
  },
  resultInfoBox: {
    marginTop: 10,
    padding: 10,
    borderRadius: INPUT_RADIUS,
    backgroundColor: "rgba(0,0,0,0.03)",
    gap: 6,
  },
  resultInfoRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  resultInfoText: {
    flex: 1,
    fontSize: FONT_SIZES.generalText,
    color: COLORS.blackText,
  },
  resultModRow: {
    flexDirection: "row",
    gap: 16,
    marginTop: 2,
  },
  resultMod: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  resultModText: {
    fontSize: FONT_SIZES.generalText,
    color: COLORS.blackText,
  },
  resultBtnRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 12,
  },
  resultBtnOutline: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 11,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: COLORS.greyBorder,
    backgroundColor: COLORS.white,
  },
  resultBtnOutlineText: {
    fontSize: FONT_SIZES.generalText,
    fontWeight: FONT_WEIGHT.medium,
    color: COLORS.blackText,
  },
  resultBtnPrimary: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 11,
    borderRadius: 999,
    backgroundColor: COLORS.secondary,
  },
  resultBtnPrimaryText: {
    fontSize: FONT_SIZES.generalText,
    fontWeight: FONT_WEIGHT.bold,
    color: COLORS.white,
  },
  resultBtnMuted: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 11,
    borderRadius: 999,
    backgroundColor: "rgba(0,0,0,0.06)",
  },
  resultBtnMutedText: {
    fontSize: FONT_SIZES.generalText,
    fontWeight: FONT_WEIGHT.medium,
    color: COLORS.blackText,
  },
  section: {
    marginTop: 24,
    backgroundColor: COLORS.white,
    borderRadius: CARD_RADIUS,
    padding: PADDINGS.screenEdge,
    ...getShadowStyle({ y: 2, blur: 8, opacity: 0.06, elevation: 2 }),
  },
  sectionTitle: {
    fontSize: FONT_SIZES.subtitle2,
    fontWeight: FONT_WEIGHT.boldFontBig,
    color: COLORS.blackText,
    marginBottom: 12,
  },
  calendarWrap: {
    marginTop: 8,
  },
  timeGroup: {
    marginBottom: PADDINGS.screenEdge,
  },
  timeGroupTitle: {
    fontSize: FONT_SIZES.inputText,
    fontWeight: FONT_WEIGHT.boldFont,
    color: COLORS.greyText,
    marginBottom: 10,
  },
  timeQuarterBlock: {
    marginTop: 16,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: "rgba(0,0,0,0.08)",
  },
  timeQuarterHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  changeHourLink: {
    fontSize: FONT_SIZES.inputText,
    color: COLORS.secondary,
    fontWeight: FONT_WEIGHT.boldFont,
  },
  clinicList: {
    gap: 0,
  },
  clinicListItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 14,
    paddingHorizontal: 8,
    marginBottom: 8,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.08)",
    backgroundColor: COLORS.white,
  },
  clinicListItemFirst: {
    borderTopWidth: 1,
  },
  // M17: selected clinic must be unmistakable — a full colored border + tint
  // + shadow (not just a subtle 3px left-border tint), matching the always-
  // visible radio indicator below.
  clinicListItemSelected: {
    backgroundColor: "rgba(112, 193, 227, 0.16)",
    borderWidth: 2,
    borderColor: COLORS.secondary,
    ...getGlassShadow({ y: 2, blur: 6, opacity: 0.12, elevation: 3 }),
  },
  // M17: always-visible radio indicator (empty ring / filled dot), so the
  // patient sees at a glance that a choice is required and which one is made.
  clinicRadioOuter: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 2,
    borderColor: COLORS.greyBorder,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  clinicRadioOuterSelected: {
    borderColor: COLORS.secondary,
  },
  clinicRadioInner: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: COLORS.secondary,
  },
  clinicNameWrap: {
    flex: 1,
  },
  clinicName: {
    fontSize: FONT_SIZES.inputText,
    fontWeight: FONT_WEIGHT.boldFont,
    color: COLORS.blackText,
  },
  clinicLocationReference: {
    fontSize: FONT_SIZES.xsText,
    color: COLORS.greyText,
    marginTop: 2,
    fontFamily: FONT_FAMILY.regular,
  },
  clinicMapsButton: {
    ...getGlassStyle("secondary"),
    padding: 8,
    marginLeft: 8,
    borderRadius: 10,
  },
  timeRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },
  timeChip: {
    width: "48%",
    marginBottom: 12,
    paddingVertical: 13,
    paddingHorizontal: 12,
    borderRadius: 12,
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: "#E4E9F0",
    alignItems: "center",
    justifyContent: "center",
    ...getShadowStyle({ y: 1, blur: 3, opacity: 0.05, elevation: 1 }),
  },
  timeChipSelected: {
    backgroundColor: COLORS.secondary,
    borderColor: COLORS.secondary,
  },
  timeChipDisabled: {
    backgroundColor: "#F0F2F5",
    borderColor: "#F0F2F5",
    ...getShadowStyle({ y: 0, blur: 0, opacity: 0, elevation: 0 }),
  },
  timeChipText: {
    fontSize: FONT_SIZES.inputText,
    color: COLORS.blackText,
    fontFamily: FONT_FAMILY.semiBold,
  },
  timeChipTextSelected: {
    color: COLORS.white,
  },
  timeChipTextDisabled: {
    color: COLORS.ligthGreyText,
  },
  typeRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginTop: 8,
  },
  typeChip: {
    marginBottom: 10,
  },
  confirmButton: {
    ...getGlassStyle("primary"),
    flexDirection: "row",
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 24,
  },
  confirmButtonDisabled: {
    opacity: 0.5,
  },
  confirmButtonText: {
    fontSize: FONT_SIZES.mediumButtonText,
    fontFamily: FONT_FAMILY.bold,
    color: COLORS.selectedItem,
  },
  loader: {
    paddingVertical: PADDINGS.screenEdge,
    alignItems: "center",
  },
  emptyText: {
    fontSize: FONT_SIZES.inputText,
    color: COLORS.greyText,
    textAlign: "center",
    marginTop: 12,
  },
  dateErrorWrap: {
    alignItems: "center",
    paddingVertical: PADDINGS.screenEdge,
  },
  retryButton: {
    ...getGlassStyle("primary"),
    marginTop: 16,
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 12,
    alignItems: "center",
  },
  retryButtonText: {
    fontSize: FONT_SIZES.inputText,
    fontWeight: FONT_WEIGHT.boldFont,
    color: COLORS.selectedItem,
  },
  // Full-height bottom sheet doctor modal (extends to full screen, with same margin on all sides)
  doctorModalSheet: {
    position: "absolute",
    left: PADDINGS.screenEdge,
    right: PADDINGS.screenEdge,
    top: PADDINGS.screenEdge,
    bottom: PADDINGS.screenEdge,
    backgroundColor: COLORS.white,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
    overflow: "hidden",
    ...getShadowStyle({ y: -4, blur: 16, opacity: 0.12, elevation: 12 }),
  },
  doctorModalHandleWrap: {
    paddingTop: PADDINGS.screenEdge,
    paddingBottom: 12,
    alignSelf: "center",
  },
  doctorModalScreen: {
    flex: 1,
    backgroundColor: COLORS.white,
  },
  doctorModalHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: PADDINGS.screenEdge,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(0,0,0,0.06)",
  },
  doctorModalBack: {
    padding: 8,
    marginLeft: -8,
  },
  doctorModalScroll: {
    flex: 1,
  },
  doctorModalScrollContent: {
    paddingHorizontal: PADDINGS.screenEdge,
    paddingBottom: 24,
    paddingTop: 28,
  },
  doctorModalCtaWrap: {
    marginTop: 24,
    marginBottom: 16,
  },
  doctorModalProfileWrap: {
    alignItems: "center",
    marginBottom: 24,
  },
  doctorModalAvatar: {
    width: 90,
    height: 90,
    borderRadius: 45,
    marginBottom: 12,
  },
  doctorModalAvatarPlaceholder: {
    width: 90,
    height: 90,
    borderRadius: 45,
    backgroundColor: COLORS.secondary,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
  },
  doctorModalName: {
    fontSize: FONT_SIZES.sectionTitleBig,
    fontWeight: FONT_WEIGHT.boldFontBig,
    color: COLORS.blackText,
    textAlign: "center",
    marginBottom: 4,
  },
  doctorModalSpecialty: {
    fontSize: FONT_SIZES.inputText,
    color: COLORS.greyText,
    textAlign: "center",
    marginBottom: 16,
  },
  doctorModalCta: {
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 12,
    backgroundColor: COLORS.secondary,
    alignSelf: "center",
    minWidth: 260,
    alignItems: "center",
  },
  doctorModalCtaText: {
    fontSize: FONT_SIZES.mediumButtonText,
    fontWeight: FONT_WEIGHT.boldFont,
    color: COLORS.whiteText,
  },
  doctorModalDivider: {
    height: 1,
    backgroundColor: "rgba(0,0,0,0.08)",
    marginVertical: PADDINGS.screenEdge,
  },
  doctorModalSection: {
    marginBottom: 8,
  },
  doctorModalSectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  doctorModalSectionIcon: {
    marginRight: 8,
  },
  doctorModalSectionTitle: {
    fontSize: FONT_SIZES.subtitle2,
    fontWeight: FONT_WEIGHT.boldFontBig,
    color: COLORS.blackText,
  },
  doctorModalLocationText: {
    fontSize: FONT_SIZES.inputText,
    color: COLORS.blackText,
    marginBottom: 12,
  },
  doctorModalClinicList: {
    marginTop: 8,
    marginBottom: 12,
  },
  doctorModalClinicRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 10,
    paddingHorizontal: 8,
    marginBottom: 8,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.08)",
    backgroundColor: COLORS.white,
  },
  doctorModalClinicRowLast: {
    marginBottom: 0,
  },
  // M17: same unmistakable-selection treatment as the booking-flow clinic list.
  doctorModalClinicRowSelected: {
    backgroundColor: "rgba(112, 193, 227, 0.16)",
    borderWidth: 2,
    borderColor: COLORS.secondary,
    ...getGlassShadow({ y: 2, blur: 6, opacity: 0.12, elevation: 3 }),
  },
  doctorModalContactRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
  },
  doctorModalContactLabel: {
    fontSize: FONT_SIZES.inputText,
    fontWeight: FONT_WEIGHT.boldFont,
    color: COLORS.greyText,
    marginRight: 6,
  },
  doctorModalContactValue: {
    fontSize: FONT_SIZES.inputText,
    color: COLORS.secondary,
    textDecorationLine: "underline",
  },
  doctorModalBio: {
    fontSize: FONT_SIZES.inputText,
    color: COLORS.blackText,
    marginBottom: 12,
    lineHeight: 22,
  },
  doctorModalChips: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginHorizontal: -4,
  },
  doctorModalChip: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 8,
    backgroundColor: "rgba(112, 193, 227, 0.2)",
    marginRight: 8,
    marginBottom: 8,
  },
  doctorModalChipText: {
    fontSize: FONT_SIZES.xsText,
    fontWeight: FONT_WEIGHT.boldFont,
    color: COLORS.secondary,
  },
  doctorModalScheduleNote: {
    fontSize: FONT_SIZES.inputText,
    color: COLORS.greyText,
    fontStyle: "italic",
  },
  doctorModalScheduleCard: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    backgroundColor: "rgba(112, 193, 227, 0.12)",
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 12,
    marginBottom: 10,
  },
  doctorModalScheduleDay: {
    fontSize: FONT_SIZES.inputText,
    fontWeight: FONT_WEIGHT.boldFont,
    color: COLORS.blackText,
  },
  doctorModalScheduleTimeRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  doctorModalScheduleTimeText: {
    fontSize: FONT_SIZES.inputText,
    color: COLORS.blackText,
    marginLeft: 6,
  },
  doctorModalSchedulePill: {
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 20,
    backgroundColor: "rgba(112, 193, 227, 0.25)",
  },
  doctorModalSchedulePillText: {
    fontSize: FONT_SIZES.xsText,
    fontWeight: FONT_WEIGHT.boldFont,
    color: COLORS.secondary,
  },
  // M13: search filters
  filterToggleButton: {
    ...getGlassStyle("secondary"),
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    gap: 6,
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 20,
    marginTop: 10,
  },
  filterToggleButtonActive: {
    backgroundColor: "rgba(112, 193, 227, 0.25)",
    borderColor: COLORS.secondary,
  },
  filterToggleButtonText: {
    fontSize: FONT_SIZES.inputText,
    color: COLORS.blackText,
    fontFamily: FONT_FAMILY.regular,
  },
  filterPanel: {
    backgroundColor: COLORS.white,
    borderRadius: CARD_RADIUS,
    borderWidth: 1,
    borderColor: COLORS.greyBorder,
    padding: 14,
    marginTop: 10,
  },
  filterSectionLabel: {
    fontSize: FONT_SIZES.xsText,
    color: COLORS.greyText,
    marginBottom: 6,
    marginTop: 10,
    fontFamily: FONT_FAMILY.regular,
  },
  filterOptionRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  filterOption: {
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: COLORS.greyBorder,
    backgroundColor: COLORS.inputBackgeound,
  },
  filterOptionSelected: {
    backgroundColor: COLORS.secondary,
    borderColor: COLORS.secondary,
  },
  filterOptionText: {
    fontSize: FONT_SIZES.inputText,
    color: COLORS.blackText,
    fontFamily: FONT_FAMILY.regular,
  },
  filterOptionTextSelected: {
    fontWeight: FONT_WEIGHT.boldFont,
  },
  filterToggleRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 10,
    gap: 8,
  },
  filterToggleLabel: {
    fontSize: FONT_SIZES.inputText,
    color: COLORS.blackText,
    fontFamily: FONT_FAMILY.regular,
    flex: 1,
  },
  filterDistanceRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginTop: 4,
  },
  filterDistanceStepper: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: COLORS.greyBorder,
    borderRadius: 10,
    overflow: "hidden",
  },
  filterDistanceStepperButton: {
    paddingVertical: 8,
    paddingHorizontal: 14,
    backgroundColor: COLORS.inputBackgeound,
  },
  filterDistanceStepperText: {
    fontSize: FONT_SIZES.inputText,
    fontWeight: FONT_WEIGHT.boldFont,
    color: COLORS.blackText,
  },
  filterDistanceValue: {
    fontSize: FONT_SIZES.inputText,
    color: COLORS.blackText,
    fontFamily: FONT_FAMILY.regular,
    minWidth: 70,
    textAlign: "center",
  },
  filterLocationHint: {
    fontSize: FONT_SIZES.xsText,
    color: COLORS.greyText,
    marginTop: 6,
    fontFamily: FONT_FAMILY.regular,
  },
  filterClearButton: {
    alignSelf: "flex-end",
    marginTop: 12,
  },
  filterClearButtonText: {
    fontSize: FONT_SIZES.inputText,
    color: COLORS.secondary,
    fontWeight: FONT_WEIGHT.boldFont,
  },

  // "Agendar Cita" header
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
    gap: 12,
  },
  headerTitle: {
    flex: 1,
    fontSize: FONT_SIZES.sectionTitleBig ?? 20,
    fontFamily: FONT_FAMILY.bold,
    color: COLORS.secondary,
  },
  headerAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: COLORS.greyBorder,
  },
  headerAvatarPlaceholder: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.secondary,
  },
  sectionSubtitle: {
    fontSize: FONT_SIZES.inputText,
    color: COLORS.greyText,
    fontFamily: FONT_FAMILY.regular,
    marginTop: -6,
    marginBottom: 12,
    lineHeight: 20,
  },

  // Waitlist toggle card
  waitlistCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#EAF3FB",
    borderRadius: 14,
    padding: 14,
    marginTop: 16,
  },
  waitlistIconWrap: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: COLORS.secondary,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  waitlistTextWrap: {
    flex: 1,
    marginRight: 8,
  },
  waitlistTitle: {
    fontSize: FONT_SIZES.inputText,
    fontFamily: FONT_FAMILY.semiBold,
    color: COLORS.blackText,
  },
  waitlistSub: {
    fontSize: FONT_SIZES.xsText,
    color: COLORS.greyText,
    fontFamily: FONT_FAMILY.regular,
    marginTop: 3,
    lineHeight: 17,
  },

  // Radio-style choice cards (family / modality)
  choiceCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.white,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: "#E4E9F0",
    padding: 14,
    marginBottom: 12,
  },
  choiceCardSelected: {
    borderColor: COLORS.secondary,
    backgroundColor: "#F4FBFE",
  },
  choiceIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 12,
    backgroundColor: "#EAF6FB",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  choiceTextWrap: {
    flex: 1,
  },
  choiceLabel: {
    fontSize: FONT_SIZES.inputText,
    fontFamily: FONT_FAMILY.semiBold,
    color: COLORS.blackText,
  },
  choiceSub: {
    fontSize: FONT_SIZES.xsText,
    color: COLORS.greyText,
    fontFamily: FONT_FAMILY.regular,
    marginTop: 2,
  },
  choiceRadioOuter: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 2,
    borderColor: COLORS.greyBorder,
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 10,
  },
  choiceRadioOuterSelected: {
    borderColor: COLORS.secondary,
  },
  choiceRadioInner: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: COLORS.secondary,
  },
  fieldLabel: {
    fontSize: FONT_SIZES.xsText,
    color: COLORS.greyText,
    fontFamily: FONT_FAMILY.regular,
    marginTop: 4,
    marginBottom: 6,
  },
});

export default styles;
