import { StyleSheet, Platform } from "react-native";
import {
  COLORS,
  FONT_SIZES,
  FONT_WEIGHT,
  FONT_FAMILY,
  PADDINGS,
  getShadowStyle,
  getGlassShadow,
} from "../../../styles/theme";

const CARD_RADIUS = 16;
const PILL_RADIUS = 24;
const HEADER_CURVE = 28;

const styles = StyleSheet.create({
  keyboardView: { flex: 1, backgroundColor: "transparent" },
  container: {
    flexGrow: 1,
    paddingBottom: PADDINGS.tabBarSafeBottom,
  },
  header: {
    backgroundColor: COLORS.secondary,
    paddingTop: Platform.OS === "web" ? 48 : PADDINGS.mainTop,
    paddingHorizontal: PADDINGS.screenEdge,
    paddingBottom: PADDINGS.screenEdge,
    borderBottomLeftRadius: HEADER_CURVE,
    borderBottomRightRadius: HEADER_CURVE,
    marginBottom: 0,
  },
  searchBarWrap: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.white,
    borderRadius: PILL_RADIUS,
    paddingHorizontal: 16,
    paddingVertical: 12,
    minHeight: 48,
    borderWidth: 1,
    borderColor: COLORS.tagColor,
  },
  searchBarInput: {
    flex: 1,
    fontSize: FONT_SIZES.inputText,
    color: COLORS.blackText,
    paddingVertical: 0,
    marginLeft: 10,
    fontFamily: FONT_FAMILY.regular,
  },
  content: {
    flex: 1,
    paddingHorizontal: PADDINGS.screenEdge,
    paddingTop: PADDINGS.screenEdge,
    backgroundColor: "transparent",
  },
  contentCenter: {
    flexGrow: 1,
    justifyContent: "center",
  },
  contentStack: {
    flexGrow: 1,
  },
  searchModeBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  searchModeTitle: {
    fontSize: FONT_SIZES.subtitle2,
    fontWeight: FONT_WEIGHT.boldFontBig,
    color: COLORS.blackText,
    fontFamily: FONT_FAMILY.semiBold,
  },
  clearSearchText: {
    fontSize: FONT_SIZES.inputText,
    color: COLORS.error,
    fontWeight: FONT_WEIGHT.boldFont,
    fontFamily: FONT_FAMILY.regular,
  },
  // ── Rich search-result cards ────────────────────────────────────────────────
  srScroll: {
    flex: 1,
  },
  srScrollContent: {
    paddingBottom: 24,
  },
  srCard: {
    flexDirection: "row",
    backgroundColor: COLORS.white,
    borderRadius: CARD_RADIUS,
    marginBottom: 14,
    overflow: "hidden",
    ...getShadowStyle({ y: 2, blur: 8, opacity: 0.08, elevation: 3 }),
  },
  srAccent: {
    width: 5,
  },
  srBody: {
    flex: 1,
    padding: 14,
  },
  srTopRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  srAvatar: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: COLORS.greyBorder,
  },
  srAvatarPlaceholder: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.secondary,
  },
  srAvatarInitials: {
    fontSize: FONT_SIZES.subtitle2,
    fontWeight: FONT_WEIGHT.boldFontBig,
    color: COLORS.whiteText,
  },
  srName: {
    fontSize: FONT_SIZES.subtitle2,
    fontWeight: FONT_WEIGHT.boldFontBig,
    color: COLORS.blackText,
  },
  srChip: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    gap: 4,
    marginTop: 5,
    paddingVertical: 3,
    paddingHorizontal: 9,
    borderRadius: 999,
    backgroundColor: "rgba(112, 193, 227, 0.15)",
  },
  srChipIcon: {
    width: 16,
    height: 16,
    borderRadius: 4,
  },
  srChipText: {
    fontSize: FONT_SIZES.xsText,
    color: COLORS.blackText,
    fontWeight: FONT_WEIGHT.boldFont,
  },
  srInfoBox: {
    marginTop: 12,
    padding: 12,
    borderRadius: 12,
    backgroundColor: "rgba(0,0,0,0.03)",
    gap: 8,
  },
  srInfoRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  srInfoText: {
    flex: 1,
    fontSize: FONT_SIZES.small,
    color: COLORS.blackText,
  },
  srModRow: {
    flexDirection: "row",
    gap: 18,
    marginTop: 2,
  },
  srMod: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  srModText: {
    fontSize: FONT_SIZES.small,
    color: COLORS.blackText,
  },
  srBtnRow: {
    flexDirection: "row",
    gap: 12,
    marginTop: 14,
  },
  srBtnOutline: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: COLORS.greyBorder,
    backgroundColor: COLORS.white,
  },
  srBtnOutlineText: {
    fontSize: FONT_SIZES.small,
    fontWeight: FONT_WEIGHT.boldFont,
    color: COLORS.blackText,
  },
  srBtnPrimary: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    borderRadius: 999,
    backgroundColor: COLORS.secondary,
  },
  srBtnPrimaryText: {
    fontSize: FONT_SIZES.small,
    fontWeight: FONT_WEIGHT.boldFontBig,
    color: COLORS.white,
  },
  srBtnMuted: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 12,
    borderRadius: 999,
    backgroundColor: "rgba(0,0,0,0.06)",
  },
  srBtnMutedText: {
    fontSize: FONT_SIZES.small,
    fontWeight: FONT_WEIGHT.boldFont,
    color: COLORS.blackText,
  },

  doctorList: {
    paddingBottom: 16,
  },
  doctorCard: {
    backgroundColor: COLORS.white,
    borderRadius: CARD_RADIUS,
    padding: 16,
    marginBottom: 12,
    flexDirection: "row",
    alignItems: "center",
    ...getShadowStyle({ y: 2, blur: 8, opacity: 0.06, elevation: 2 }),
  },
  doctorCardText: {
    flex: 1,
  },
  doctorCardName: {
    fontSize: FONT_SIZES.inputText,
    fontWeight: FONT_WEIGHT.boldFont,
    color: COLORS.blackText,
    fontFamily: FONT_FAMILY.regular,
  },
  doctorCardSpecialty: {
    fontSize: FONT_SIZES.xsText,
    color: COLORS.greyText,
    marginTop: 2,
    fontFamily: FONT_FAMILY.regular,
  },
  card: {
    backgroundColor: COLORS.white,
    borderRadius: CARD_RADIUS,
    padding: PADDINGS.screenEdge,
    marginBottom: 16,
    ...getShadowStyle({ y: 2, blur: 8, opacity: 0.06, elevation: 2 }),
  },
  sectionTitle: {
    fontSize: FONT_SIZES.subtitle2,
    fontWeight: FONT_WEIGHT.boldFontBig,
    color: COLORS.blackText,
    marginBottom: 12,
    fontFamily: FONT_FAMILY.semiBold,
  },
  appointmentRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(0,0,0,0.06)",
  },
  appointmentRowLast: {
    borderBottomWidth: 0,
  },
  appointmentTime: {
    fontSize: FONT_SIZES.xsText,
    color: COLORS.greyText,
    marginRight: 12,
    minWidth: 56,
    fontFamily: FONT_FAMILY.regular,
  },
  appointmentDoctor: {
    flex: 1,
    fontSize: FONT_SIZES.inputText,
    fontWeight: FONT_WEIGHT.boldFont,
    color: COLORS.blackText,
    fontFamily: FONT_FAMILY.regular,
  },
  appointmentType: {
    fontSize: FONT_SIZES.xsText,
    color: COLORS.greyText,
    marginTop: 2,
    fontFamily: FONT_FAMILY.regular,
  },
  seeAllLink: {
    marginTop: 8,
    paddingVertical: 4,
  },
  seeAllText: {
    fontSize: FONT_SIZES.inputText,
    color: COLORS.secondary,
    fontWeight: FONT_WEIGHT.boldFont,
    fontFamily: FONT_FAMILY.regular,
  },
  greetingCard: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 16,
    paddingHorizontal: 0,
    marginBottom: 16,
  },
  greetingTextWrap: {
    flex: 1,
    marginRight: 16,
  },
  greetingTitle: {
    fontSize: FONT_SIZES.sectionTitleBig,
    fontWeight: FONT_WEIGHT.boldFontBig,
    color: COLORS.blackText,
    fontFamily: FONT_FAMILY.semiBold,
    marginBottom: 4,
  },
  greetingSubtitle: {
    fontSize: FONT_SIZES.inputText,
    color: COLORS.greyText,
    fontFamily: FONT_FAMILY.regular,
    lineHeight: 22,
  },
  greetingAvatar: {
    width: 60,
    height: 60,
    borderRadius: 30,
  },
  greetingAvatarPlaceholder: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: COLORS.secondary,
    alignItems: "center",
    justifyContent: "center",
  },
  greetingAvatarInitials: {
    fontSize: FONT_SIZES.subtitle1,
    fontWeight: FONT_WEIGHT.boldFont,
    color: COLORS.whiteText,
    fontFamily: FONT_FAMILY.semiBold,
  },
  welfareCard: {
    backgroundColor: COLORS.white,
    borderRadius: CARD_RADIUS,
    padding: 24,
    alignItems: "center",
    marginBottom: 16,
    ...getShadowStyle({ y: 2, blur: 8, opacity: 0.06, elevation: 2 }),
  },
  welfareTitle: {
    fontSize: FONT_SIZES.subtitle1,
    fontWeight: FONT_WEIGHT.boldFontBig,
    color: COLORS.blackText,
    fontFamily: FONT_FAMILY.semiBold,
    marginBottom: 8,
    textAlign: "center",
  },
  welfareSubtitle: {
    fontSize: FONT_SIZES.inputText,
    color: COLORS.greyText,
    textAlign: "center",
    lineHeight: 22,
    fontFamily: FONT_FAMILY.regular,
  },
  welfareIcon: {
    width: 80,
    height: 80,
    marginBottom: 16,
  },
  appointmentsSection: {
    marginTop: 8,
    marginBottom: 24,
  },
  homeAppointmentCard: {
    width: "100%",
    marginHorizontal: 0,
    padding: 14,
    borderRadius: CARD_RADIUS,
    marginBottom: 16,
    ...getShadowStyle({ y: 2, blur: 8, opacity: 0.06, elevation: 2 }),
  },
  homeCardHeaderRow: { marginBottom: 6 },
  homeCardDoctorSpecialty: { marginTop: 1 },
  homeCardDateRow: { marginBottom: 2 },
  homeCardTimeRow: { marginBottom: 2 },
  homeCardTimeRemaining: { marginBottom: 2 },
  homeCardActionsRow: { marginTop: 8 },
  loader: {
    paddingVertical: 24,
    alignItems: "center",
  },
  emptyText: {
    fontSize: FONT_SIZES.inputText,
    color: COLORS.greyText,
    textAlign: "center",
    paddingVertical: 24,
    fontFamily: FONT_FAMILY.regular,
  },

  // ===== New dashboard (Home) =====
  dashScrollContent: {
    paddingHorizontal: 20,
    paddingBottom: PADDINGS.tabBarSafeBottom ?? 140,
  },
  dashCard: {
    backgroundColor: COLORS.white,
    borderRadius: 20,
    padding: 18,
    marginBottom: 24,
    ...getShadowStyle({ y: 4, blur: 12, opacity: 0.06, elevation: 3 }),
  },
  dashCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  dashCardTitle: {
    fontSize: FONT_SIZES.subtitle1,
    fontWeight: FONT_WEIGHT.boldFontBig,
    color: COLORS.blackText,
    fontFamily: FONT_FAMILY.semiBold,
  },
  dashBadge: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 0,
    paddingVertical: 5,
  },
  pulsingDot: {
    width: 7,
    height: 7,
    borderRadius: 3.5,
    backgroundColor: COLORS.green,
    marginRight: 6,
  },
  dashBadgeText: {
    fontSize: FONT_SIZES.small ?? 12,
    color: COLORS.secondary,
    fontWeight: FONT_WEIGHT.boldFont,
    fontFamily: FONT_FAMILY.semiBold,
  },
  dashCardDate: {
    fontSize: FONT_SIZES.inputText,
    color: COLORS.greyText,
    fontFamily: FONT_FAMILY.regular,
    marginTop: 2,
    marginBottom: 14,
  },
  dashEmptyText: {
    fontSize: FONT_SIZES.inputText,
    color: COLORS.greyText,
    fontFamily: FONT_FAMILY.regular,
    marginTop: 10,
  },
  dashInnerRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.lightBackground ?? "rgba(112,193,227,0.10)",
    borderRadius: 14,
    padding: 12,
  },
  dashInnerAvatar: { width: 44, height: 44, borderRadius: 22 },
  dashInnerAvatarPlaceholder: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: COLORS.secondary,
    alignItems: "center",
    justifyContent: "center",
  },
  dashInnerAvatarInitials: {
    fontSize: FONT_SIZES.inputText,
    fontWeight: FONT_WEIGHT.boldFont,
    color: COLORS.whiteText,
    fontFamily: FONT_FAMILY.semiBold,
  },
  dashInnerTextWrap: { flex: 1, marginLeft: 12 },
  dashInnerName: {
    fontSize: FONT_SIZES.inputText,
    fontWeight: FONT_WEIGHT.boldFont,
    color: COLORS.blackText,
    fontFamily: FONT_FAMILY.semiBold,
  },
  dashInnerSub: {
    fontSize: FONT_SIZES.small ?? 13,
    color: COLORS.secondary,
    fontFamily: FONT_FAMILY.regular,
    marginTop: 2,
  },
  dashSection: { marginBottom: 24 },
  dashSectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 14,
  },
  dashSectionTitle: {
    fontSize: FONT_SIZES.subtitle1,
    fontWeight: FONT_WEIGHT.boldFontBig,
    color: COLORS.blackText,
    fontFamily: FONT_FAMILY.semiBold,
  },
  dashSeeAll: {
    fontSize: FONT_SIZES.inputText,
    color: COLORS.secondary,
    fontWeight: FONT_WEIGHT.boldFont,
    fontFamily: FONT_FAMILY.semiBold,
  },
  chipRow: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  chip: {
    alignItems: "center",
    width: "23%",
  },
  chipIconWrap: {
    width: "100%",
    aspectRatio: 1,
    backgroundColor: COLORS.white,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 8,
    ...getShadowStyle({ y: 2, blur: 8, opacity: 0.05, elevation: 2 }),
  },
  chipImage: {
    width: 54,
    height: 54,
  },
  chipLabel: {
    fontSize: FONT_SIZES.small ?? 12,
    color: COLORS.blackText,
    fontFamily: FONT_FAMILY.semiBold,
    textAlign: "center",
  },
  favCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.white,
    borderRadius: 18,
    padding: 12,
    marginBottom: 14,
    ...getShadowStyle({ y: 2, blur: 8, opacity: 0.06, elevation: 2 }),
  },
  favAvatar: { width: 52, height: 52, borderRadius: 26 },
  favAvatarPlaceholder: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: COLORS.secondary,
    alignItems: "center",
    justifyContent: "center",
  },
  favAvatarInitials: {
    fontSize: FONT_SIZES.inputText,
    fontWeight: FONT_WEIGHT.boldFont,
    color: COLORS.whiteText,
    fontFamily: FONT_FAMILY.semiBold,
  },
  favTextWrap: { flex: 1, marginLeft: 12, marginRight: 8 },
  favName: {
    fontSize: FONT_SIZES.inputText,
    fontWeight: FONT_WEIGHT.boldFont,
    color: COLORS.blackText,
    fontFamily: FONT_FAMILY.semiBold,
  },
  favSub: {
    fontSize: FONT_SIZES.small ?? 13,
    color: COLORS.greyText,
    fontFamily: FONT_FAMILY.regular,
    marginTop: 2,
  },
  favBookBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "rgba(255,255,255,0.28)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.6)",
    alignItems: "center",
    justifyContent: "center",
    ...getGlassShadow({ y: 2, blur: 8, opacity: 0.08 }),
  },
  specialtyModalOverlay: {
    flex: 1,
    backgroundColor: COLORS.modalOverlay ?? "rgba(0,0,0,0.4)",
    justifyContent: "center",
    paddingHorizontal: 24,
  },
  specialtyModalCard: {
    backgroundColor: COLORS.white,
    borderRadius: 20,
    padding: 20,
    maxHeight: "70%",
  },
  specialtyModalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  specialtyModalTitle: {
    fontSize: FONT_SIZES.subtitle1,
    fontWeight: FONT_WEIGHT.boldFontBig,
    color: COLORS.blackText,
    fontFamily: FONT_FAMILY.semiBold,
  },
  specialtyModalRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.tagColor,
  },
  specialtyModalRowText: {
    flex: 1,
    fontSize: FONT_SIZES.inputText,
    color: COLORS.blackText,
    fontFamily: FONT_FAMILY.regular,
  },
  specialtyModalRowIcon: {
    width: 30,
    height: 30,
    marginRight: 12,
  },
});

export default styles;
